/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by typebuilder-gen. DO NOT EDIT.

package v1beta1

import (
	json "encoding/json"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

// ServiceReferenceBuilder represents an declarative configuration of the ServiceReference type for use
// with apply.
type ServiceReferenceBuilder struct {
	fields serviceReferenceFields
}

// serviceReferenceFields owns all fields except inlined fields.
// Inline fields are owned by their respective inline type in ServiceReferenceBuilder.
// They are copied to this type before marshalling, and are copied out
// after unmarshalling. The inlined types cannot be embedded because they do
// not expose their fields directly.
type serviceReferenceFields struct {
	Namespace *string `json:"namespace,omitempty"`
	Name      *string `json:"name,omitempty"`
	Path      *string `json:"path,omitempty"`
	Port      *int32  `json:"port,omitempty"`
}

// ServiceReference constructs an declarative configuration of the ServiceReference type for use with
// apply.
func ServiceReference() *ServiceReferenceBuilder {
	return &ServiceReferenceBuilder{}
}

// SetNamespace sets the Namespace field in the declarative configuration to the given value.
func (b *ServiceReferenceBuilder) SetNamespace(value string) *ServiceReferenceBuilder {
	b.fields.Namespace = &value
	return b
}

// RemoveNamespace removes the Namespace field from the declarative configuration.
func (b *ServiceReferenceBuilder) RemoveNamespace() *ServiceReferenceBuilder {
	b.fields.Namespace = nil
	return b
}

// GetNamespace gets the Namespace field from the declarative configuration.
func (b *ServiceReferenceBuilder) GetNamespace() (value string, ok bool) {
	if v := b.fields.Namespace; v != nil {
		return *v, true
	}
	return value, false
}

// SetName sets the Name field in the declarative configuration to the given value.
func (b *ServiceReferenceBuilder) SetName(value string) *ServiceReferenceBuilder {
	b.fields.Name = &value
	return b
}

// RemoveName removes the Name field from the declarative configuration.
func (b *ServiceReferenceBuilder) RemoveName() *ServiceReferenceBuilder {
	b.fields.Name = nil
	return b
}

// GetName gets the Name field from the declarative configuration.
func (b *ServiceReferenceBuilder) GetName() (value string, ok bool) {
	if v := b.fields.Name; v != nil {
		return *v, true
	}
	return value, false
}

// SetPath sets the Path field in the declarative configuration to the given value.
func (b *ServiceReferenceBuilder) SetPath(value string) *ServiceReferenceBuilder {
	b.fields.Path = &value
	return b
}

// RemovePath removes the Path field from the declarative configuration.
func (b *ServiceReferenceBuilder) RemovePath() *ServiceReferenceBuilder {
	b.fields.Path = nil
	return b
}

// GetPath gets the Path field from the declarative configuration.
func (b *ServiceReferenceBuilder) GetPath() (value string, ok bool) {
	if v := b.fields.Path; v != nil {
		return *v, true
	}
	return value, false
}

// SetPort sets the Port field in the declarative configuration to the given value.
func (b *ServiceReferenceBuilder) SetPort(value int32) *ServiceReferenceBuilder {
	b.fields.Port = &value
	return b
}

// RemovePort removes the Port field from the declarative configuration.
func (b *ServiceReferenceBuilder) RemovePort() *ServiceReferenceBuilder {
	b.fields.Port = nil
	return b
}

// GetPort gets the Port field from the declarative configuration.
func (b *ServiceReferenceBuilder) GetPort() (value int32, ok bool) {
	if v := b.fields.Port; v != nil {
		return *v, true
	}
	return value, false
}

// ToUnstructured converts ServiceReferenceBuilder to unstructured.
func (b *ServiceReferenceBuilder) ToUnstructured() interface{} {
	if b == nil {
		return nil
	}
	b.preMarshal()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(&b.fields)
	if err != nil {
		panic(err)
	}
	return u
}

// FromUnstructured converts unstructured to ServiceReferenceBuilder, replacing the contents
// of ServiceReferenceBuilder.
func (b *ServiceReferenceBuilder) FromUnstructured(u map[string]interface{}) error {
	m := &serviceReferenceFields{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u, m)
	if err != nil {
		return err
	}
	b.fields = *m
	b.postUnmarshal()
	return nil
}

// MarshalJSON marshals ServiceReferenceBuilder to JSON.
func (b *ServiceReferenceBuilder) MarshalJSON() ([]byte, error) {
	b.preMarshal()
	return json.Marshal(b.fields)
}

// UnmarshalJSON unmarshals JSON into ServiceReferenceBuilder, replacing the contents of
// ServiceReferenceBuilder.
func (b *ServiceReferenceBuilder) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &b.fields); err != nil {
		return err
	}
	b.postUnmarshal()
	return nil
}

// ServiceReferenceList represents a list of ServiceReferenceBuilder.
type ServiceReferenceList []*ServiceReferenceBuilder

// ServiceReferenceList represents a map of ServiceReferenceBuilder.
type ServiceReferenceMap map[string]ServiceReferenceBuilder

func (b *ServiceReferenceBuilder) preMarshal() {
}
func (b *ServiceReferenceBuilder) postUnmarshal() {
}
