/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by typebuilder-gen. DO NOT EDIT.

package v2beta2

import (
	json "encoding/json"

	v2beta2 "k8s.io/api/autoscaling/v2beta2"
	resource "k8s.io/apimachinery/pkg/api/resource"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// MetricTargetBuilder represents an declarative configuration of the MetricTarget type for use
// with apply.
type MetricTargetBuilder struct {
	fields metricTargetFields
}

// metricTargetFields owns all fields except inlined fields.
// Inline fields are owned by their respective inline type in MetricTargetBuilder.
// They are copied to this type before marshalling, and are copied out
// after unmarshalling. The inlined types cannot be embedded because they do
// not expose their fields directly.
type metricTargetFields struct {
	Type               *v2beta2.MetricTargetType `json:"type,omitempty"`
	Value              *resource.Quantity        `json:"value,omitempty"`
	AverageValue       *resource.Quantity        `json:"averageValue,omitempty"`
	AverageUtilization *int32                    `json:"averageUtilization,omitempty"`
}

// MetricTarget constructs an declarative configuration of the MetricTarget type for use with
// apply.
func MetricTarget() *MetricTargetBuilder {
	return &MetricTargetBuilder{}
}

// SetType sets the Type field in the declarative configuration to the given value.
func (b *MetricTargetBuilder) SetType(value v2beta2.MetricTargetType) *MetricTargetBuilder {
	b.fields.Type = &value
	return b
}

// RemoveType removes the Type field from the declarative configuration.
func (b *MetricTargetBuilder) RemoveType() *MetricTargetBuilder {
	b.fields.Type = nil
	return b
}

// GetType gets the Type field from the declarative configuration.
func (b *MetricTargetBuilder) GetType() (value v2beta2.MetricTargetType, ok bool) {
	if v := b.fields.Type; v != nil {
		return *v, true
	}
	return value, false
}

// SetValue sets the Value field in the declarative configuration to the given value.
func (b *MetricTargetBuilder) SetValue(value resource.Quantity) *MetricTargetBuilder {
	b.fields.Value = &value
	return b
}

// RemoveValue removes the Value field from the declarative configuration.
func (b *MetricTargetBuilder) RemoveValue() *MetricTargetBuilder {
	b.fields.Value = nil
	return b
}

// GetValue gets the Value field from the declarative configuration.
func (b *MetricTargetBuilder) GetValue() (value resource.Quantity, ok bool) {
	if v := b.fields.Value; v != nil {
		return *v, true
	}
	return value, false
}

// SetAverageValue sets the AverageValue field in the declarative configuration to the given value.
func (b *MetricTargetBuilder) SetAverageValue(value resource.Quantity) *MetricTargetBuilder {
	b.fields.AverageValue = &value
	return b
}

// RemoveAverageValue removes the AverageValue field from the declarative configuration.
func (b *MetricTargetBuilder) RemoveAverageValue() *MetricTargetBuilder {
	b.fields.AverageValue = nil
	return b
}

// GetAverageValue gets the AverageValue field from the declarative configuration.
func (b *MetricTargetBuilder) GetAverageValue() (value resource.Quantity, ok bool) {
	if v := b.fields.AverageValue; v != nil {
		return *v, true
	}
	return value, false
}

// SetAverageUtilization sets the AverageUtilization field in the declarative configuration to the given value.
func (b *MetricTargetBuilder) SetAverageUtilization(value int32) *MetricTargetBuilder {
	b.fields.AverageUtilization = &value
	return b
}

// RemoveAverageUtilization removes the AverageUtilization field from the declarative configuration.
func (b *MetricTargetBuilder) RemoveAverageUtilization() *MetricTargetBuilder {
	b.fields.AverageUtilization = nil
	return b
}

// GetAverageUtilization gets the AverageUtilization field from the declarative configuration.
func (b *MetricTargetBuilder) GetAverageUtilization() (value int32, ok bool) {
	if v := b.fields.AverageUtilization; v != nil {
		return *v, true
	}
	return value, false
}

// ToUnstructured converts MetricTargetBuilder to unstructured.
func (b *MetricTargetBuilder) ToUnstructured() interface{} {
	if b == nil {
		return nil
	}
	b.preMarshal()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(&b.fields)
	if err != nil {
		panic(err)
	}
	return u
}

// FromUnstructured converts unstructured to MetricTargetBuilder, replacing the contents
// of MetricTargetBuilder.
func (b *MetricTargetBuilder) FromUnstructured(u map[string]interface{}) error {
	m := &metricTargetFields{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u, m)
	if err != nil {
		return err
	}
	b.fields = *m
	b.postUnmarshal()
	return nil
}

// MarshalJSON marshals MetricTargetBuilder to JSON.
func (b *MetricTargetBuilder) MarshalJSON() ([]byte, error) {
	b.preMarshal()
	return json.Marshal(b.fields)
}

// UnmarshalJSON unmarshals JSON into MetricTargetBuilder, replacing the contents of
// MetricTargetBuilder.
func (b *MetricTargetBuilder) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &b.fields); err != nil {
		return err
	}
	b.postUnmarshal()
	return nil
}

// MetricTargetList represents a list of MetricTargetBuilder.
type MetricTargetList []*MetricTargetBuilder

// MetricTargetList represents a map of MetricTargetBuilder.
type MetricTargetMap map[string]MetricTargetBuilder

func (b *MetricTargetBuilder) preMarshal() {
}
func (b *MetricTargetBuilder) postUnmarshal() {
}
