/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by typebuilder-gen. DO NOT EDIT.

package v1beta1

import (
	json "encoding/json"

	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/client-go/typebuilders/meta/v1"
)

// LocalSubjectAccessReviewBuilder represents an declarative configuration of the LocalSubjectAccessReview type for use
// with apply.
type LocalSubjectAccessReviewBuilder struct {
	typeMeta *v1.TypeMetaBuilder // inlined type
	fields   localSubjectAccessReviewFields
}

// localSubjectAccessReviewFields owns all fields except inlined fields.
// Inline fields are owned by their respective inline type in LocalSubjectAccessReviewBuilder.
// They are copied to this type before marshalling, and are copied out
// after unmarshalling. The inlined types cannot be embedded because they do
// not expose their fields directly.
type localSubjectAccessReviewFields struct {
	Kind       *string                           `json:"kind,omitempty"`       // inlined LocalSubjectAccessReviewBuilder.typeMeta.Kind field
	APIVersion *string                           `json:"apiVersion,omitempty"` // inlined LocalSubjectAccessReviewBuilder.typeMeta.APIVersion field
	ObjectMeta *v1.ObjectMetaBuilder             `json:"metadata,omitempty"`
	Spec       *SubjectAccessReviewSpecBuilder   `json:"spec,omitempty"`
	Status     *SubjectAccessReviewStatusBuilder `json:"status,omitempty"`
}

// LocalSubjectAccessReview constructs an declarative configuration of the LocalSubjectAccessReview type for use with
// apply.
func LocalSubjectAccessReview() *LocalSubjectAccessReviewBuilder {
	return &LocalSubjectAccessReviewBuilder{}
}

// SetTypeMeta sets the TypeMeta field in the declarative configuration to the given value.
func (b *LocalSubjectAccessReviewBuilder) SetTypeMeta(value *v1.TypeMetaBuilder) *LocalSubjectAccessReviewBuilder {
	b.typeMeta = value
	return b
}

// RemoveTypeMeta removes the TypeMeta field from the declarative configuration.
func (b *LocalSubjectAccessReviewBuilder) RemoveTypeMeta() *LocalSubjectAccessReviewBuilder {
	b.typeMeta = nil
	return b
}

// GetTypeMeta gets the TypeMeta field from the declarative configuration.
func (b *LocalSubjectAccessReviewBuilder) GetTypeMeta() (value *v1.TypeMetaBuilder, ok bool) {
	return b.typeMeta, true
}

// SetObjectMeta sets the ObjectMeta field in the declarative configuration to the given value.
func (b *LocalSubjectAccessReviewBuilder) SetObjectMeta(value *v1.ObjectMetaBuilder) *LocalSubjectAccessReviewBuilder {
	b.fields.ObjectMeta = value
	return b
}

// RemoveObjectMeta removes the ObjectMeta field from the declarative configuration.
func (b *LocalSubjectAccessReviewBuilder) RemoveObjectMeta() *LocalSubjectAccessReviewBuilder {
	b.fields.ObjectMeta = nil
	return b
}

// GetObjectMeta gets the ObjectMeta field from the declarative configuration.
func (b *LocalSubjectAccessReviewBuilder) GetObjectMeta() (value *v1.ObjectMetaBuilder, ok bool) {
	return b.fields.ObjectMeta, b.fields.ObjectMeta != nil
}

// SetSpec sets the Spec field in the declarative configuration to the given value.
func (b *LocalSubjectAccessReviewBuilder) SetSpec(value *SubjectAccessReviewSpecBuilder) *LocalSubjectAccessReviewBuilder {
	b.fields.Spec = value
	return b
}

// RemoveSpec removes the Spec field from the declarative configuration.
func (b *LocalSubjectAccessReviewBuilder) RemoveSpec() *LocalSubjectAccessReviewBuilder {
	b.fields.Spec = nil
	return b
}

// GetSpec gets the Spec field from the declarative configuration.
func (b *LocalSubjectAccessReviewBuilder) GetSpec() (value *SubjectAccessReviewSpecBuilder, ok bool) {
	return b.fields.Spec, b.fields.Spec != nil
}

// SetStatus sets the Status field in the declarative configuration to the given value.
func (b *LocalSubjectAccessReviewBuilder) SetStatus(value *SubjectAccessReviewStatusBuilder) *LocalSubjectAccessReviewBuilder {
	b.fields.Status = value
	return b
}

// RemoveStatus removes the Status field from the declarative configuration.
func (b *LocalSubjectAccessReviewBuilder) RemoveStatus() *LocalSubjectAccessReviewBuilder {
	b.fields.Status = nil
	return b
}

// GetStatus gets the Status field from the declarative configuration.
func (b *LocalSubjectAccessReviewBuilder) GetStatus() (value *SubjectAccessReviewStatusBuilder, ok bool) {
	return b.fields.Status, b.fields.Status != nil
}

// ToUnstructured converts LocalSubjectAccessReviewBuilder to unstructured.
func (b *LocalSubjectAccessReviewBuilder) ToUnstructured() interface{} {
	if b == nil {
		return nil
	}
	b.preMarshal()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(&b.fields)
	if err != nil {
		panic(err)
	}
	return u
}

// FromUnstructured converts unstructured to LocalSubjectAccessReviewBuilder, replacing the contents
// of LocalSubjectAccessReviewBuilder.
func (b *LocalSubjectAccessReviewBuilder) FromUnstructured(u map[string]interface{}) error {
	m := &localSubjectAccessReviewFields{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u, m)
	if err != nil {
		return err
	}
	b.fields = *m
	b.postUnmarshal()
	return nil
}

// MarshalJSON marshals LocalSubjectAccessReviewBuilder to JSON.
func (b *LocalSubjectAccessReviewBuilder) MarshalJSON() ([]byte, error) {
	b.preMarshal()
	return json.Marshal(b.fields)
}

// UnmarshalJSON unmarshals JSON into LocalSubjectAccessReviewBuilder, replacing the contents of
// LocalSubjectAccessReviewBuilder.
func (b *LocalSubjectAccessReviewBuilder) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &b.fields); err != nil {
		return err
	}
	b.postUnmarshal()
	return nil
}

// LocalSubjectAccessReviewList represents a list of LocalSubjectAccessReviewBuilder.
type LocalSubjectAccessReviewList []*LocalSubjectAccessReviewBuilder

// LocalSubjectAccessReviewList represents a map of LocalSubjectAccessReviewBuilder.
type LocalSubjectAccessReviewMap map[string]LocalSubjectAccessReviewBuilder

func (b *LocalSubjectAccessReviewBuilder) preMarshal() {
	if b.typeMeta != nil {
		if v, ok := b.typeMeta.GetKind(); ok {
			b.fields.Kind = &v
		}
		if v, ok := b.typeMeta.GetAPIVersion(); ok {
			b.fields.APIVersion = &v
		}
	}
}
func (b *LocalSubjectAccessReviewBuilder) postUnmarshal() {
	if b.typeMeta == nil {
		b.typeMeta = &v1.TypeMetaBuilder{}
	}
	if b.fields.Kind != nil {
		b.typeMeta.SetKind(*b.fields.Kind)
	}
	if b.fields.APIVersion != nil {
		b.typeMeta.SetAPIVersion(*b.fields.APIVersion)
	}
}
