/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	json "encoding/json"

	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// VolumeAttachmentApplyConfiguration represents an declarative configuration of the VolumeAttachment type for use
// with apply.
type VolumeAttachmentApplyConfiguration struct {
	typeMeta *v1.TypeMetaApplyConfiguration // inlined type
	fields   volumeAttachmentFields
}

// VolumeAttachmentApplyConfiguration constructs an declarative configuration of the VolumeAttachment type for use with
// apply.
func VolumeAttachment() *VolumeAttachmentApplyConfiguration {
	return &VolumeAttachmentApplyConfiguration{}
}

// volumeAttachmentFields owns all fields except inlined fields.
// Inline fields are owned by their respective inline type in VolumeAttachmentApplyConfiguration.
// They are copied to this type before marshalling, and are copied out
// after unmarshalling. The inlined types cannot be embedded because they do
// not expose their fields directly.
type volumeAttachmentFields struct {
	Kind       *string                                   `json:"kind,omitempty"`       // inlined VolumeAttachmentApplyConfiguration.typeMeta.Kind field
	APIVersion *string                                   `json:"apiVersion,omitempty"` // inlined VolumeAttachmentApplyConfiguration.typeMeta.APIVersion field
	ObjectMeta *v1.ObjectMetaApplyConfiguration          `json:"metadata,omitempty"`
	Spec       *VolumeAttachmentSpecApplyConfiguration   `json:"spec,omitempty"`
	Status     *VolumeAttachmentStatusApplyConfiguration `json:"status,omitempty"`
}

// SetTypeMeta sets the TypeMeta field in the declarative configuration to the given value.
func (b *VolumeAttachmentApplyConfiguration) SetTypeMeta(value *v1.TypeMetaApplyConfiguration) *VolumeAttachmentApplyConfiguration {
	b.typeMeta = value
	return b
}

// RemoveTypeMeta removes the TypeMeta field from the declarative configuration.
func (b *VolumeAttachmentApplyConfiguration) RemoveTypeMeta() *VolumeAttachmentApplyConfiguration {
	b.typeMeta = nil
	return b
}

// GetTypeMeta gets the TypeMeta field from the declarative configuration.
func (b *VolumeAttachmentApplyConfiguration) GetTypeMeta() (value *v1.TypeMetaApplyConfiguration, ok bool) {
	return b.typeMeta, true
}

// SetObjectMeta sets the ObjectMeta field in the declarative configuration to the given value.
func (b *VolumeAttachmentApplyConfiguration) SetObjectMeta(value *v1.ObjectMetaApplyConfiguration) *VolumeAttachmentApplyConfiguration {
	b.fields.ObjectMeta = value
	return b
}

// RemoveObjectMeta removes the ObjectMeta field from the declarative configuration.
func (b *VolumeAttachmentApplyConfiguration) RemoveObjectMeta() *VolumeAttachmentApplyConfiguration {
	b.fields.ObjectMeta = nil
	return b
}

// GetObjectMeta gets the ObjectMeta field from the declarative configuration.
func (b *VolumeAttachmentApplyConfiguration) GetObjectMeta() (value *v1.ObjectMetaApplyConfiguration, ok bool) {
	return b.fields.ObjectMeta, b.fields.ObjectMeta != nil
}

// SetSpec sets the Spec field in the declarative configuration to the given value.
func (b *VolumeAttachmentApplyConfiguration) SetSpec(value *VolumeAttachmentSpecApplyConfiguration) *VolumeAttachmentApplyConfiguration {
	b.fields.Spec = value
	return b
}

// RemoveSpec removes the Spec field from the declarative configuration.
func (b *VolumeAttachmentApplyConfiguration) RemoveSpec() *VolumeAttachmentApplyConfiguration {
	b.fields.Spec = nil
	return b
}

// GetSpec gets the Spec field from the declarative configuration.
func (b *VolumeAttachmentApplyConfiguration) GetSpec() (value *VolumeAttachmentSpecApplyConfiguration, ok bool) {
	return b.fields.Spec, b.fields.Spec != nil
}

// SetStatus sets the Status field in the declarative configuration to the given value.
func (b *VolumeAttachmentApplyConfiguration) SetStatus(value *VolumeAttachmentStatusApplyConfiguration) *VolumeAttachmentApplyConfiguration {
	b.fields.Status = value
	return b
}

// RemoveStatus removes the Status field from the declarative configuration.
func (b *VolumeAttachmentApplyConfiguration) RemoveStatus() *VolumeAttachmentApplyConfiguration {
	b.fields.Status = nil
	return b
}

// GetStatus gets the Status field from the declarative configuration.
func (b *VolumeAttachmentApplyConfiguration) GetStatus() (value *VolumeAttachmentStatusApplyConfiguration, ok bool) {
	return b.fields.Status, b.fields.Status != nil
}

// ToUnstructured converts VolumeAttachmentApplyConfiguration to unstructured.
func (b *VolumeAttachmentApplyConfiguration) ToUnstructured() interface{} {
	if b == nil {
		return nil
	}
	b.preMarshal()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(&b.fields)
	if err != nil {
		panic(err)
	}
	return u
}

// FromUnstructured converts unstructured to VolumeAttachmentApplyConfiguration, replacing the contents
// of VolumeAttachmentApplyConfiguration.
func (b *VolumeAttachmentApplyConfiguration) FromUnstructured(u map[string]interface{}) error {
	m := &volumeAttachmentFields{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u, m)
	if err != nil {
		return err
	}
	b.fields = *m
	b.postUnmarshal()
	return nil
}

// MarshalJSON marshals VolumeAttachmentApplyConfiguration to JSON.
func (b *VolumeAttachmentApplyConfiguration) MarshalJSON() ([]byte, error) {
	b.preMarshal()
	return json.Marshal(b.fields)
}

// UnmarshalJSON unmarshals JSON into VolumeAttachmentApplyConfiguration, replacing the contents of
// VolumeAttachmentApplyConfiguration.
func (b *VolumeAttachmentApplyConfiguration) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &b.fields); err != nil {
		return err
	}
	b.postUnmarshal()
	return nil
}

// VolumeAttachmentList represents a listAlias of VolumeAttachmentApplyConfiguration.
type VolumeAttachmentList []*VolumeAttachmentApplyConfiguration

// VolumeAttachmentList represents a map of VolumeAttachmentApplyConfiguration.
type VolumeAttachmentMap map[string]VolumeAttachmentApplyConfiguration

func (b *VolumeAttachmentApplyConfiguration) preMarshal() {
	if b.typeMeta != nil {
		if v, ok := b.typeMeta.GetKind(); ok {
			b.fields.Kind = &v
		}
		if v, ok := b.typeMeta.GetAPIVersion(); ok {
			b.fields.APIVersion = &v
		}
	}
}
func (b *VolumeAttachmentApplyConfiguration) postUnmarshal() {
	if b.typeMeta == nil {
		b.typeMeta = &v1.TypeMetaApplyConfiguration{}
	}
	if b.fields.Kind != nil {
		b.typeMeta.SetKind(*b.fields.Kind)
	}
	if b.fields.APIVersion != nil {
		b.typeMeta.SetAPIVersion(*b.fields.APIVersion)
	}
}
