/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by typebuilder-gen. DO NOT EDIT.

package v1beta1

import (
	json "encoding/json"

	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/client-go/typebuilders/meta/v1"
)

// CSINodeBuilder represents an declarative configuration of the CSINode type for use
// with apply.
type CSINodeBuilder struct {
	typeMeta v1.TypeMetaBuilder // inlined type
	fields   *cSINodeFields
}

// cSINodeFields is used by CSINodeBuilder for json marshalling and unmarshalling.
// Is the source-of-truth for all fields except inlined fields.
// Inline fields are copied in from their builder type in CSINodeBuilder before marshalling, and
// are copied out to the builder type in CSINodeBuilder after unmarshalling.
// Inlined builder types cannot be embedded because they do not expose their fields directly.
type cSINodeFields struct {
	Kind       *string               `json:"kind,omitempty"`       // inlined CSINodeBuilder.typeMeta.Kind field
	APIVersion *string               `json:"apiVersion,omitempty"` // inlined CSINodeBuilder.typeMeta.APIVersion field
	ObjectMeta *v1.ObjectMetaBuilder `json:"metadata,omitempty"`
	Spec       *CSINodeSpecBuilder   `json:"spec,omitempty"`
}

func (b *CSINodeBuilder) ensureInitialized() {
	if b.fields == nil {
		b.fields = &cSINodeFields{}
	}
}

// CSINode constructs an declarative configuration of the CSINode type for use with
// apply.
// Provided as a convenience.
func CSINode() CSINodeBuilder {
	return CSINodeBuilder{fields: &cSINodeFields{}}
}

// SetTypeMeta sets the TypeMeta field in the declarative configuration to the given value.
func (b CSINodeBuilder) SetTypeMeta(value v1.TypeMetaBuilder) CSINodeBuilder {
	b.ensureInitialized()
	b.typeMeta = value
	return b
}

// RemoveTypeMeta removes the TypeMeta field from the declarative configuration.
func (b CSINodeBuilder) RemoveTypeMeta() CSINodeBuilder {
	b.ensureInitialized()
	b.typeMeta = v1.TypeMetaBuilder{}
	return b
}

// GetTypeMeta gets the TypeMeta field from the declarative configuration.
func (b CSINodeBuilder) GetTypeMeta() (value v1.TypeMetaBuilder, ok bool) {
	b.ensureInitialized()
	return b.typeMeta, true
}

// SetObjectMeta sets the ObjectMeta field in the declarative configuration to the given value.
func (b CSINodeBuilder) SetObjectMeta(value v1.ObjectMetaBuilder) CSINodeBuilder {
	b.ensureInitialized()
	b.fields.ObjectMeta = &value
	return b
}

// RemoveObjectMeta removes the ObjectMeta field from the declarative configuration.
func (b CSINodeBuilder) RemoveObjectMeta() CSINodeBuilder {
	b.ensureInitialized()
	b.fields.ObjectMeta = nil
	return b
}

// GetObjectMeta gets the ObjectMeta field from the declarative configuration.
func (b CSINodeBuilder) GetObjectMeta() (value v1.ObjectMetaBuilder, ok bool) {
	b.ensureInitialized()
	if v := b.fields.ObjectMeta; v != nil {
		return *v, true
	}
	return value, false
}

// SetSpec sets the Spec field in the declarative configuration to the given value.
func (b CSINodeBuilder) SetSpec(value CSINodeSpecBuilder) CSINodeBuilder {
	b.ensureInitialized()
	b.fields.Spec = &value
	return b
}

// RemoveSpec removes the Spec field from the declarative configuration.
func (b CSINodeBuilder) RemoveSpec() CSINodeBuilder {
	b.ensureInitialized()
	b.fields.Spec = nil
	return b
}

// GetSpec gets the Spec field from the declarative configuration.
func (b CSINodeBuilder) GetSpec() (value CSINodeSpecBuilder, ok bool) {
	b.ensureInitialized()
	if v := b.fields.Spec; v != nil {
		return *v, true
	}
	return value, false
}

// ToUnstructured converts CSINodeBuilder to unstructured.
func (b *CSINodeBuilder) ToUnstructured() interface{} {
	if b == nil {
		return nil
	}
	b.ensureInitialized()
	b.preMarshal()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(b.fields)
	if err != nil {
		panic(err)
	}
	return u
}

// FromUnstructured converts unstructured to CSINodeBuilder, replacing the contents
// of CSINodeBuilder.
func (b *CSINodeBuilder) FromUnstructured(u map[string]interface{}) error {
	m := &cSINodeFields{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u, m)
	if err != nil {
		return err
	}
	b.fields = m
	b.postUnmarshal()
	return nil
}

// MarshalJSON marshals CSINodeBuilder to JSON.
func (b *CSINodeBuilder) MarshalJSON() ([]byte, error) {
	u := &unstructured.Unstructured{Object: b.ToUnstructured().(map[string]interface{})}
	return u.MarshalJSON()
}

// UnmarshalJSON unmarshals JSON into CSINodeBuilder, replacing the contents of
// CSINodeBuilder.
func (b *CSINodeBuilder) UnmarshalJSON(data []byte) error {
	b.ensureInitialized()
	if err := json.Unmarshal(data, b.fields); err != nil {
		return err
	}
	b.postUnmarshal()
	return nil
}

// CSINodeList represents a list of CSINodeBuilder.
// Provided as a convenience.
type CSINodeList []CSINodeBuilder

// CSINodeList represents a map of CSINodeBuilder.
// Provided as a convenience.
type CSINodeMap map[string]CSINodeBuilder

func (b *CSINodeBuilder) preMarshal() {
	if v, ok := b.typeMeta.GetKind(); ok {
		b.fields.Kind = &v
	}
	if v, ok := b.typeMeta.GetAPIVersion(); ok {
		b.fields.APIVersion = &v
	}
}
func (b *CSINodeBuilder) postUnmarshal() {
	if b.fields.Kind != nil {
		b.typeMeta.SetKind(*b.fields.Kind)
	}
	if b.fields.APIVersion != nil {
		b.typeMeta.SetAPIVersion(*b.fields.APIVersion)
	}
}
