/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// NonResourceRuleApplyConfiguration represents an declarative configuration of the NonResourceRule type for use
// with apply.
type NonResourceRuleApplyConfiguration struct {
	Verbs           *[]string `json:"verbs,omitempty"`
	NonResourceURLs *[]string `json:"nonResourceURLs,omitempty"`
}

// NonResourceRuleApplyConfiguration constructs an declarative configuration of the NonResourceRule type for use with
// apply.
func NonResourceRule() *NonResourceRuleApplyConfiguration {
	return &NonResourceRuleApplyConfiguration{}
}

// SetVerbs sets the Verbs field in the declarative configuration to the given value.
func (b *NonResourceRuleApplyConfiguration) SetVerbs(value []string) *NonResourceRuleApplyConfiguration {
	b.Verbs = &value
	return b
}

// SetNonResourceURLs sets the NonResourceURLs field in the declarative configuration to the given value.
func (b *NonResourceRuleApplyConfiguration) SetNonResourceURLs(value []string) *NonResourceRuleApplyConfiguration {
	b.NonResourceURLs = &value
	return b
}
