/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by typebuilder-gen. DO NOT EDIT.

package v1

import (
	json "encoding/json"

	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// PersistentVolumeClaimConditionBuilder represents an declarative configuration of the PersistentVolumeClaimCondition type for use
// with apply.
type PersistentVolumeClaimConditionBuilder struct {
	fields *persistentVolumeClaimConditionFields
}

// persistentVolumeClaimConditionFields is used by PersistentVolumeClaimConditionBuilder for json marshalling and unmarshalling.
// Is the source-of-truth for all fields except inlined fields.
// Inline fields are copied in from their builder type in PersistentVolumeClaimConditionBuilder before marshalling, and
// are copied out to the builder type in PersistentVolumeClaimConditionBuilder after unmarshalling.
// Inlined builder types cannot be embedded because they do not expose their fields directly.
type persistentVolumeClaimConditionFields struct {
	Type               *v1.PersistentVolumeClaimConditionType `json:"type,omitempty"`
	Status             *v1.ConditionStatus                    `json:"status,omitempty"`
	LastProbeTime      *metav1.Time                           `json:"lastProbeTime,omitempty"`
	LastTransitionTime *metav1.Time                           `json:"lastTransitionTime,omitempty"`
	Reason             *string                                `json:"reason,omitempty"`
	Message            *string                                `json:"message,omitempty"`
}

func (b *PersistentVolumeClaimConditionBuilder) ensureInitialized() {
	if b.fields == nil {
		b.fields = &persistentVolumeClaimConditionFields{}
	}
}

// PersistentVolumeClaimCondition constructs an declarative configuration of the PersistentVolumeClaimCondition type for use with
// apply.
// Provided as a convenience.
func PersistentVolumeClaimCondition() PersistentVolumeClaimConditionBuilder {
	return PersistentVolumeClaimConditionBuilder{fields: &persistentVolumeClaimConditionFields{}}
}

// SetType sets the Type field in the declarative configuration to the given value.
func (b PersistentVolumeClaimConditionBuilder) SetType(value v1.PersistentVolumeClaimConditionType) PersistentVolumeClaimConditionBuilder {
	b.ensureInitialized()
	b.fields.Type = &value
	return b
}

// RemoveType removes the Type field from the declarative configuration.
func (b PersistentVolumeClaimConditionBuilder) RemoveType() PersistentVolumeClaimConditionBuilder {
	b.ensureInitialized()
	b.fields.Type = nil
	return b
}

// GetType gets the Type field from the declarative configuration.
func (b PersistentVolumeClaimConditionBuilder) GetType() (value v1.PersistentVolumeClaimConditionType, ok bool) {
	b.ensureInitialized()
	if v := b.fields.Type; v != nil {
		return *v, true
	}
	return value, false
}

// SetStatus sets the Status field in the declarative configuration to the given value.
func (b PersistentVolumeClaimConditionBuilder) SetStatus(value v1.ConditionStatus) PersistentVolumeClaimConditionBuilder {
	b.ensureInitialized()
	b.fields.Status = &value
	return b
}

// RemoveStatus removes the Status field from the declarative configuration.
func (b PersistentVolumeClaimConditionBuilder) RemoveStatus() PersistentVolumeClaimConditionBuilder {
	b.ensureInitialized()
	b.fields.Status = nil
	return b
}

// GetStatus gets the Status field from the declarative configuration.
func (b PersistentVolumeClaimConditionBuilder) GetStatus() (value v1.ConditionStatus, ok bool) {
	b.ensureInitialized()
	if v := b.fields.Status; v != nil {
		return *v, true
	}
	return value, false
}

// SetLastProbeTime sets the LastProbeTime field in the declarative configuration to the given value.
func (b PersistentVolumeClaimConditionBuilder) SetLastProbeTime(value metav1.Time) PersistentVolumeClaimConditionBuilder {
	b.ensureInitialized()
	b.fields.LastProbeTime = &value
	return b
}

// RemoveLastProbeTime removes the LastProbeTime field from the declarative configuration.
func (b PersistentVolumeClaimConditionBuilder) RemoveLastProbeTime() PersistentVolumeClaimConditionBuilder {
	b.ensureInitialized()
	b.fields.LastProbeTime = nil
	return b
}

// GetLastProbeTime gets the LastProbeTime field from the declarative configuration.
func (b PersistentVolumeClaimConditionBuilder) GetLastProbeTime() (value metav1.Time, ok bool) {
	b.ensureInitialized()
	if v := b.fields.LastProbeTime; v != nil {
		return *v, true
	}
	return value, false
}

// SetLastTransitionTime sets the LastTransitionTime field in the declarative configuration to the given value.
func (b PersistentVolumeClaimConditionBuilder) SetLastTransitionTime(value metav1.Time) PersistentVolumeClaimConditionBuilder {
	b.ensureInitialized()
	b.fields.LastTransitionTime = &value
	return b
}

// RemoveLastTransitionTime removes the LastTransitionTime field from the declarative configuration.
func (b PersistentVolumeClaimConditionBuilder) RemoveLastTransitionTime() PersistentVolumeClaimConditionBuilder {
	b.ensureInitialized()
	b.fields.LastTransitionTime = nil
	return b
}

// GetLastTransitionTime gets the LastTransitionTime field from the declarative configuration.
func (b PersistentVolumeClaimConditionBuilder) GetLastTransitionTime() (value metav1.Time, ok bool) {
	b.ensureInitialized()
	if v := b.fields.LastTransitionTime; v != nil {
		return *v, true
	}
	return value, false
}

// SetReason sets the Reason field in the declarative configuration to the given value.
func (b PersistentVolumeClaimConditionBuilder) SetReason(value string) PersistentVolumeClaimConditionBuilder {
	b.ensureInitialized()
	b.fields.Reason = &value
	return b
}

// RemoveReason removes the Reason field from the declarative configuration.
func (b PersistentVolumeClaimConditionBuilder) RemoveReason() PersistentVolumeClaimConditionBuilder {
	b.ensureInitialized()
	b.fields.Reason = nil
	return b
}

// GetReason gets the Reason field from the declarative configuration.
func (b PersistentVolumeClaimConditionBuilder) GetReason() (value string, ok bool) {
	b.ensureInitialized()
	if v := b.fields.Reason; v != nil {
		return *v, true
	}
	return value, false
}

// SetMessage sets the Message field in the declarative configuration to the given value.
func (b PersistentVolumeClaimConditionBuilder) SetMessage(value string) PersistentVolumeClaimConditionBuilder {
	b.ensureInitialized()
	b.fields.Message = &value
	return b
}

// RemoveMessage removes the Message field from the declarative configuration.
func (b PersistentVolumeClaimConditionBuilder) RemoveMessage() PersistentVolumeClaimConditionBuilder {
	b.ensureInitialized()
	b.fields.Message = nil
	return b
}

// GetMessage gets the Message field from the declarative configuration.
func (b PersistentVolumeClaimConditionBuilder) GetMessage() (value string, ok bool) {
	b.ensureInitialized()
	if v := b.fields.Message; v != nil {
		return *v, true
	}
	return value, false
}

// ToUnstructured converts PersistentVolumeClaimConditionBuilder to unstructured.
func (b *PersistentVolumeClaimConditionBuilder) ToUnstructured() interface{} {
	if b == nil {
		return nil
	}
	b.ensureInitialized()
	b.preMarshal()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(b.fields)
	if err != nil {
		panic(err)
	}
	return u
}

// FromUnstructured converts unstructured to PersistentVolumeClaimConditionBuilder, replacing the contents
// of PersistentVolumeClaimConditionBuilder.
func (b *PersistentVolumeClaimConditionBuilder) FromUnstructured(u map[string]interface{}) error {
	m := &persistentVolumeClaimConditionFields{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u, m)
	if err != nil {
		return err
	}
	b.fields = m
	b.postUnmarshal()
	return nil
}

// MarshalJSON marshals PersistentVolumeClaimConditionBuilder to JSON.
func (b *PersistentVolumeClaimConditionBuilder) MarshalJSON() ([]byte, error) {
	u := &unstructured.Unstructured{Object: b.ToUnstructured().(map[string]interface{})}
	return u.MarshalJSON()
}

// UnmarshalJSON unmarshals JSON into PersistentVolumeClaimConditionBuilder, replacing the contents of
// PersistentVolumeClaimConditionBuilder.
func (b *PersistentVolumeClaimConditionBuilder) UnmarshalJSON(data []byte) error {
	b.ensureInitialized()
	if err := json.Unmarshal(data, b.fields); err != nil {
		return err
	}
	b.postUnmarshal()
	return nil
}

// PersistentVolumeClaimConditionList represents a list of PersistentVolumeClaimConditionBuilder.
// Provided as a convenience.
type PersistentVolumeClaimConditionList []PersistentVolumeClaimConditionBuilder

// PersistentVolumeClaimConditionList represents a map of PersistentVolumeClaimConditionBuilder.
// Provided as a convenience.
type PersistentVolumeClaimConditionMap map[string]PersistentVolumeClaimConditionBuilder

func (b *PersistentVolumeClaimConditionBuilder) preMarshal() {
}
func (b *PersistentVolumeClaimConditionBuilder) postUnmarshal() {
}
