/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by typebuilder-gen. DO NOT EDIT.

package v1

import (
	json "encoding/json"

	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// PodSecurityContextBuilder represents an declarative configuration of the PodSecurityContext type for use
// with apply.
type PodSecurityContextBuilder struct {
	fields *podSecurityContextFields
}

// podSecurityContextFields is used by PodSecurityContextBuilder for json marshalling and unmarshalling.
// Is the source-of-truth for all fields except inlined fields.
// Inline fields are copied in from their builder type in PodSecurityContextBuilder before marshalling, and
// are copied out to the builder type in PodSecurityContextBuilder after unmarshalling.
// Inlined builder types cannot be embedded because they do not expose their fields directly.
type podSecurityContextFields struct {
	SELinuxOptions      *SELinuxOptionsBuilder                `json:"seLinuxOptions,omitempty"`
	WindowsOptions      *WindowsSecurityContextOptionsBuilder `json:"windowsOptions,omitempty"`
	RunAsUser           *int64                                `json:"runAsUser,omitempty"`
	RunAsGroup          *int64                                `json:"runAsGroup,omitempty"`
	RunAsNonRoot        *bool                                 `json:"runAsNonRoot,omitempty"`
	SupplementalGroups  *[]int64                              `json:"supplementalGroups,omitempty"`
	FSGroup             *int64                                `json:"fsGroup,omitempty"`
	Sysctls             *SysctlList                           `json:"sysctls,omitempty"`
	FSGroupChangePolicy *corev1.PodFSGroupChangePolicy        `json:"fsGroupChangePolicy,omitempty"`
	SeccompProfile      *SeccompProfileBuilder                `json:"seccompProfile,omitempty"`
}

func (b *PodSecurityContextBuilder) ensureInitialized() {
	if b.fields == nil {
		b.fields = &podSecurityContextFields{}
	}
}

// PodSecurityContext constructs an declarative configuration of the PodSecurityContext type for use with
// apply.
// Provided as a convenience.
func PodSecurityContext() PodSecurityContextBuilder {
	return PodSecurityContextBuilder{fields: &podSecurityContextFields{}}
}

// SetSELinuxOptions sets the SELinuxOptions field in the declarative configuration to the given value.
func (b PodSecurityContextBuilder) SetSELinuxOptions(value SELinuxOptionsBuilder) PodSecurityContextBuilder {
	b.ensureInitialized()
	b.fields.SELinuxOptions = &value
	return b
}

// RemoveSELinuxOptions removes the SELinuxOptions field from the declarative configuration.
func (b PodSecurityContextBuilder) RemoveSELinuxOptions() PodSecurityContextBuilder {
	b.ensureInitialized()
	b.fields.SELinuxOptions = nil
	return b
}

// GetSELinuxOptions gets the SELinuxOptions field from the declarative configuration.
func (b PodSecurityContextBuilder) GetSELinuxOptions() (value SELinuxOptionsBuilder, ok bool) {
	b.ensureInitialized()
	if v := b.fields.SELinuxOptions; v != nil {
		return *v, true
	}
	return value, false
}

// SetWindowsOptions sets the WindowsOptions field in the declarative configuration to the given value.
func (b PodSecurityContextBuilder) SetWindowsOptions(value WindowsSecurityContextOptionsBuilder) PodSecurityContextBuilder {
	b.ensureInitialized()
	b.fields.WindowsOptions = &value
	return b
}

// RemoveWindowsOptions removes the WindowsOptions field from the declarative configuration.
func (b PodSecurityContextBuilder) RemoveWindowsOptions() PodSecurityContextBuilder {
	b.ensureInitialized()
	b.fields.WindowsOptions = nil
	return b
}

// GetWindowsOptions gets the WindowsOptions field from the declarative configuration.
func (b PodSecurityContextBuilder) GetWindowsOptions() (value WindowsSecurityContextOptionsBuilder, ok bool) {
	b.ensureInitialized()
	if v := b.fields.WindowsOptions; v != nil {
		return *v, true
	}
	return value, false
}

// SetRunAsUser sets the RunAsUser field in the declarative configuration to the given value.
func (b PodSecurityContextBuilder) SetRunAsUser(value int64) PodSecurityContextBuilder {
	b.ensureInitialized()
	b.fields.RunAsUser = &value
	return b
}

// RemoveRunAsUser removes the RunAsUser field from the declarative configuration.
func (b PodSecurityContextBuilder) RemoveRunAsUser() PodSecurityContextBuilder {
	b.ensureInitialized()
	b.fields.RunAsUser = nil
	return b
}

// GetRunAsUser gets the RunAsUser field from the declarative configuration.
func (b PodSecurityContextBuilder) GetRunAsUser() (value int64, ok bool) {
	b.ensureInitialized()
	if v := b.fields.RunAsUser; v != nil {
		return *v, true
	}
	return value, false
}

// SetRunAsGroup sets the RunAsGroup field in the declarative configuration to the given value.
func (b PodSecurityContextBuilder) SetRunAsGroup(value int64) PodSecurityContextBuilder {
	b.ensureInitialized()
	b.fields.RunAsGroup = &value
	return b
}

// RemoveRunAsGroup removes the RunAsGroup field from the declarative configuration.
func (b PodSecurityContextBuilder) RemoveRunAsGroup() PodSecurityContextBuilder {
	b.ensureInitialized()
	b.fields.RunAsGroup = nil
	return b
}

// GetRunAsGroup gets the RunAsGroup field from the declarative configuration.
func (b PodSecurityContextBuilder) GetRunAsGroup() (value int64, ok bool) {
	b.ensureInitialized()
	if v := b.fields.RunAsGroup; v != nil {
		return *v, true
	}
	return value, false
}

// SetRunAsNonRoot sets the RunAsNonRoot field in the declarative configuration to the given value.
func (b PodSecurityContextBuilder) SetRunAsNonRoot(value bool) PodSecurityContextBuilder {
	b.ensureInitialized()
	b.fields.RunAsNonRoot = &value
	return b
}

// RemoveRunAsNonRoot removes the RunAsNonRoot field from the declarative configuration.
func (b PodSecurityContextBuilder) RemoveRunAsNonRoot() PodSecurityContextBuilder {
	b.ensureInitialized()
	b.fields.RunAsNonRoot = nil
	return b
}

// GetRunAsNonRoot gets the RunAsNonRoot field from the declarative configuration.
func (b PodSecurityContextBuilder) GetRunAsNonRoot() (value bool, ok bool) {
	b.ensureInitialized()
	if v := b.fields.RunAsNonRoot; v != nil {
		return *v, true
	}
	return value, false
}

// SetSupplementalGroups sets the SupplementalGroups field in the declarative configuration to the given value.
func (b PodSecurityContextBuilder) SetSupplementalGroups(value []int64) PodSecurityContextBuilder {
	b.ensureInitialized()
	b.fields.SupplementalGroups = &value
	return b
}

// RemoveSupplementalGroups removes the SupplementalGroups field from the declarative configuration.
func (b PodSecurityContextBuilder) RemoveSupplementalGroups() PodSecurityContextBuilder {
	b.ensureInitialized()
	b.fields.SupplementalGroups = nil
	return b
}

// GetSupplementalGroups gets the SupplementalGroups field from the declarative configuration.
func (b PodSecurityContextBuilder) GetSupplementalGroups() (value []int64, ok bool) {
	b.ensureInitialized()
	if v := b.fields.SupplementalGroups; v != nil {
		return *v, true
	}
	return value, false
}

// SetFSGroup sets the FSGroup field in the declarative configuration to the given value.
func (b PodSecurityContextBuilder) SetFSGroup(value int64) PodSecurityContextBuilder {
	b.ensureInitialized()
	b.fields.FSGroup = &value
	return b
}

// RemoveFSGroup removes the FSGroup field from the declarative configuration.
func (b PodSecurityContextBuilder) RemoveFSGroup() PodSecurityContextBuilder {
	b.ensureInitialized()
	b.fields.FSGroup = nil
	return b
}

// GetFSGroup gets the FSGroup field from the declarative configuration.
func (b PodSecurityContextBuilder) GetFSGroup() (value int64, ok bool) {
	b.ensureInitialized()
	if v := b.fields.FSGroup; v != nil {
		return *v, true
	}
	return value, false
}

// SetSysctls sets the Sysctls field in the declarative configuration to the given value.
func (b PodSecurityContextBuilder) SetSysctls(value SysctlList) PodSecurityContextBuilder {
	b.ensureInitialized()
	b.fields.Sysctls = &value
	return b
}

// RemoveSysctls removes the Sysctls field from the declarative configuration.
func (b PodSecurityContextBuilder) RemoveSysctls() PodSecurityContextBuilder {
	b.ensureInitialized()
	b.fields.Sysctls = nil
	return b
}

// GetSysctls gets the Sysctls field from the declarative configuration.
func (b PodSecurityContextBuilder) GetSysctls() (value SysctlList, ok bool) {
	b.ensureInitialized()
	if v := b.fields.Sysctls; v != nil {
		return *v, true
	}
	return value, false
}

// SetFSGroupChangePolicy sets the FSGroupChangePolicy field in the declarative configuration to the given value.
func (b PodSecurityContextBuilder) SetFSGroupChangePolicy(value corev1.PodFSGroupChangePolicy) PodSecurityContextBuilder {
	b.ensureInitialized()
	b.fields.FSGroupChangePolicy = &value
	return b
}

// RemoveFSGroupChangePolicy removes the FSGroupChangePolicy field from the declarative configuration.
func (b PodSecurityContextBuilder) RemoveFSGroupChangePolicy() PodSecurityContextBuilder {
	b.ensureInitialized()
	b.fields.FSGroupChangePolicy = nil
	return b
}

// GetFSGroupChangePolicy gets the FSGroupChangePolicy field from the declarative configuration.
func (b PodSecurityContextBuilder) GetFSGroupChangePolicy() (value corev1.PodFSGroupChangePolicy, ok bool) {
	b.ensureInitialized()
	if v := b.fields.FSGroupChangePolicy; v != nil {
		return *v, true
	}
	return value, false
}

// SetSeccompProfile sets the SeccompProfile field in the declarative configuration to the given value.
func (b PodSecurityContextBuilder) SetSeccompProfile(value SeccompProfileBuilder) PodSecurityContextBuilder {
	b.ensureInitialized()
	b.fields.SeccompProfile = &value
	return b
}

// RemoveSeccompProfile removes the SeccompProfile field from the declarative configuration.
func (b PodSecurityContextBuilder) RemoveSeccompProfile() PodSecurityContextBuilder {
	b.ensureInitialized()
	b.fields.SeccompProfile = nil
	return b
}

// GetSeccompProfile gets the SeccompProfile field from the declarative configuration.
func (b PodSecurityContextBuilder) GetSeccompProfile() (value SeccompProfileBuilder, ok bool) {
	b.ensureInitialized()
	if v := b.fields.SeccompProfile; v != nil {
		return *v, true
	}
	return value, false
}

// ToUnstructured converts PodSecurityContextBuilder to unstructured.
func (b *PodSecurityContextBuilder) ToUnstructured() interface{} {
	if b == nil {
		return nil
	}
	b.ensureInitialized()
	b.preMarshal()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(b.fields)
	if err != nil {
		panic(err)
	}
	return u
}

// FromUnstructured converts unstructured to PodSecurityContextBuilder, replacing the contents
// of PodSecurityContextBuilder.
func (b *PodSecurityContextBuilder) FromUnstructured(u map[string]interface{}) error {
	m := &podSecurityContextFields{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u, m)
	if err != nil {
		return err
	}
	b.fields = m
	b.postUnmarshal()
	return nil
}

// MarshalJSON marshals PodSecurityContextBuilder to JSON.
func (b *PodSecurityContextBuilder) MarshalJSON() ([]byte, error) {
	b.ensureInitialized()
	b.preMarshal()
	return json.Marshal(b.fields)
}

// UnmarshalJSON unmarshals JSON into PodSecurityContextBuilder, replacing the contents of
// PodSecurityContextBuilder.
func (b *PodSecurityContextBuilder) UnmarshalJSON(data []byte) error {
	b.ensureInitialized()
	if err := json.Unmarshal(data, b.fields); err != nil {
		return err
	}
	b.postUnmarshal()
	return nil
}

// PodSecurityContextList represents a list of PodSecurityContextBuilder.
// Provided as a convenience.
type PodSecurityContextList []PodSecurityContextBuilder

// PodSecurityContextList represents a map of PodSecurityContextBuilder.
// Provided as a convenience.
type PodSecurityContextMap map[string]PodSecurityContextBuilder

func (b *PodSecurityContextBuilder) preMarshal() {
}
func (b *PodSecurityContextBuilder) postUnmarshal() {
}
