/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by typebuilder-gen. DO NOT EDIT.

package v1

import (
	json "encoding/json"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

// SecretVolumeSourceBuilder represents an declarative configuration of the SecretVolumeSource type for use
// with apply.
type SecretVolumeSourceBuilder struct {
	fields *secretVolumeSourceFields
}

// secretVolumeSourceFields is used by SecretVolumeSourceBuilder for json marshalling and unmarshalling.
// Is the source-of-truth for all fields except inlined fields.
// Inline fields are copied in from their builder type in SecretVolumeSourceBuilder before marshalling, and
// are copied out to the builder type in SecretVolumeSourceBuilder after unmarshalling.
// Inlined builder types cannot be embedded because they do not expose their fields directly.
type secretVolumeSourceFields struct {
	SecretName  *string        `json:"secretName,omitempty"`
	Items       *KeyToPathList `json:"items,omitempty"`
	DefaultMode *int32         `json:"defaultMode,omitempty"`
	Optional    *bool          `json:"optional,omitempty"`
}

func (b *SecretVolumeSourceBuilder) ensureInitialized() {
	if b.fields == nil {
		b.fields = &secretVolumeSourceFields{}
	}
}

// SecretVolumeSource constructs an declarative configuration of the SecretVolumeSource type for use with
// apply.
// Provided as a convenience.
func SecretVolumeSource() SecretVolumeSourceBuilder {
	return SecretVolumeSourceBuilder{fields: &secretVolumeSourceFields{}}
}

// SetSecretName sets the SecretName field in the declarative configuration to the given value.
func (b SecretVolumeSourceBuilder) SetSecretName(value string) SecretVolumeSourceBuilder {
	b.ensureInitialized()
	b.fields.SecretName = &value
	return b
}

// RemoveSecretName removes the SecretName field from the declarative configuration.
func (b SecretVolumeSourceBuilder) RemoveSecretName() SecretVolumeSourceBuilder {
	b.ensureInitialized()
	b.fields.SecretName = nil
	return b
}

// GetSecretName gets the SecretName field from the declarative configuration.
func (b SecretVolumeSourceBuilder) GetSecretName() (value string, ok bool) {
	b.ensureInitialized()
	if v := b.fields.SecretName; v != nil {
		return *v, true
	}
	return value, false
}

// SetItems sets the Items field in the declarative configuration to the given value.
func (b SecretVolumeSourceBuilder) SetItems(value KeyToPathList) SecretVolumeSourceBuilder {
	b.ensureInitialized()
	b.fields.Items = &value
	return b
}

// RemoveItems removes the Items field from the declarative configuration.
func (b SecretVolumeSourceBuilder) RemoveItems() SecretVolumeSourceBuilder {
	b.ensureInitialized()
	b.fields.Items = nil
	return b
}

// GetItems gets the Items field from the declarative configuration.
func (b SecretVolumeSourceBuilder) GetItems() (value KeyToPathList, ok bool) {
	b.ensureInitialized()
	if v := b.fields.Items; v != nil {
		return *v, true
	}
	return value, false
}

// SetDefaultMode sets the DefaultMode field in the declarative configuration to the given value.
func (b SecretVolumeSourceBuilder) SetDefaultMode(value int32) SecretVolumeSourceBuilder {
	b.ensureInitialized()
	b.fields.DefaultMode = &value
	return b
}

// RemoveDefaultMode removes the DefaultMode field from the declarative configuration.
func (b SecretVolumeSourceBuilder) RemoveDefaultMode() SecretVolumeSourceBuilder {
	b.ensureInitialized()
	b.fields.DefaultMode = nil
	return b
}

// GetDefaultMode gets the DefaultMode field from the declarative configuration.
func (b SecretVolumeSourceBuilder) GetDefaultMode() (value int32, ok bool) {
	b.ensureInitialized()
	if v := b.fields.DefaultMode; v != nil {
		return *v, true
	}
	return value, false
}

// SetOptional sets the Optional field in the declarative configuration to the given value.
func (b SecretVolumeSourceBuilder) SetOptional(value bool) SecretVolumeSourceBuilder {
	b.ensureInitialized()
	b.fields.Optional = &value
	return b
}

// RemoveOptional removes the Optional field from the declarative configuration.
func (b SecretVolumeSourceBuilder) RemoveOptional() SecretVolumeSourceBuilder {
	b.ensureInitialized()
	b.fields.Optional = nil
	return b
}

// GetOptional gets the Optional field from the declarative configuration.
func (b SecretVolumeSourceBuilder) GetOptional() (value bool, ok bool) {
	b.ensureInitialized()
	if v := b.fields.Optional; v != nil {
		return *v, true
	}
	return value, false
}

// ToUnstructured converts SecretVolumeSourceBuilder to unstructured.
func (b *SecretVolumeSourceBuilder) ToUnstructured() interface{} {
	if b == nil {
		return nil
	}
	b.ensureInitialized()
	b.preMarshal()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(b.fields)
	if err != nil {
		panic(err)
	}
	return u
}

// FromUnstructured converts unstructured to SecretVolumeSourceBuilder, replacing the contents
// of SecretVolumeSourceBuilder.
func (b *SecretVolumeSourceBuilder) FromUnstructured(u map[string]interface{}) error {
	m := &secretVolumeSourceFields{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u, m)
	if err != nil {
		return err
	}
	b.fields = m
	b.postUnmarshal()
	return nil
}

// MarshalJSON marshals SecretVolumeSourceBuilder to JSON.
func (b *SecretVolumeSourceBuilder) MarshalJSON() ([]byte, error) {
	b.ensureInitialized()
	b.preMarshal()
	return json.Marshal(b.fields)
}

// UnmarshalJSON unmarshals JSON into SecretVolumeSourceBuilder, replacing the contents of
// SecretVolumeSourceBuilder.
func (b *SecretVolumeSourceBuilder) UnmarshalJSON(data []byte) error {
	b.ensureInitialized()
	if err := json.Unmarshal(data, b.fields); err != nil {
		return err
	}
	b.postUnmarshal()
	return nil
}

// SecretVolumeSourceList represents a list of SecretVolumeSourceBuilder.
// Provided as a convenience.
type SecretVolumeSourceList []SecretVolumeSourceBuilder

// SecretVolumeSourceList represents a map of SecretVolumeSourceBuilder.
// Provided as a convenience.
type SecretVolumeSourceMap map[string]SecretVolumeSourceBuilder

func (b *SecretVolumeSourceBuilder) preMarshal() {
}
func (b *SecretVolumeSourceBuilder) postUnmarshal() {
}
