/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by typebuilder-gen. DO NOT EDIT.

package v1

import (
	json "encoding/json"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

// SysctlBuilder represents an declarative configuration of the Sysctl type for use
// with apply.
type SysctlBuilder struct {
	fields sysctlFields
}

// sysctlFields owns all fields except inlined fields.
// Inline fields are owned by their respective inline type in SysctlBuilder.
// They are copied to this type before marshalling, and are copied out
// after unmarshalling. The inlined types cannot be embedded because they do
// not expose their fields directly.
type sysctlFields struct {
	Name  *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
}

// Sysctl constructs an declarative configuration of the Sysctl type for use with
// apply.
func Sysctl() *SysctlBuilder {
	return &SysctlBuilder{}
}

// SetName sets the Name field in the declarative configuration to the given value.
func (b *SysctlBuilder) SetName(value string) *SysctlBuilder {
	b.fields.Name = &value
	return b
}

// RemoveName removes the Name field from the declarative configuration.
func (b *SysctlBuilder) RemoveName() *SysctlBuilder {
	b.fields.Name = nil
	return b
}

// GetName gets the Name field from the declarative configuration.
func (b *SysctlBuilder) GetName() (value string, ok bool) {
	if v := b.fields.Name; v != nil {
		return *v, true
	}
	return value, false
}

// SetValue sets the Value field in the declarative configuration to the given value.
func (b *SysctlBuilder) SetValue(value string) *SysctlBuilder {
	b.fields.Value = &value
	return b
}

// RemoveValue removes the Value field from the declarative configuration.
func (b *SysctlBuilder) RemoveValue() *SysctlBuilder {
	b.fields.Value = nil
	return b
}

// GetValue gets the Value field from the declarative configuration.
func (b *SysctlBuilder) GetValue() (value string, ok bool) {
	if v := b.fields.Value; v != nil {
		return *v, true
	}
	return value, false
}

// ToUnstructured converts SysctlBuilder to unstructured.
func (b *SysctlBuilder) ToUnstructured() interface{} {
	if b == nil {
		return nil
	}
	b.preMarshal()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(&b.fields)
	if err != nil {
		panic(err)
	}
	return u
}

// FromUnstructured converts unstructured to SysctlBuilder, replacing the contents
// of SysctlBuilder.
func (b *SysctlBuilder) FromUnstructured(u map[string]interface{}) error {
	m := &sysctlFields{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u, m)
	if err != nil {
		return err
	}
	b.fields = *m
	b.postUnmarshal()
	return nil
}

// MarshalJSON marshals SysctlBuilder to JSON.
func (b *SysctlBuilder) MarshalJSON() ([]byte, error) {
	b.preMarshal()
	return json.Marshal(b.fields)
}

// UnmarshalJSON unmarshals JSON into SysctlBuilder, replacing the contents of
// SysctlBuilder.
func (b *SysctlBuilder) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &b.fields); err != nil {
		return err
	}
	b.postUnmarshal()
	return nil
}

// SysctlList represents a list of SysctlBuilder.
type SysctlList []*SysctlBuilder

// SysctlList represents a map of SysctlBuilder.
type SysctlMap map[string]SysctlBuilder

func (b *SysctlBuilder) preMarshal() {
}
func (b *SysctlBuilder) postUnmarshal() {
}
