/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by typebuilder-gen. DO NOT EDIT.

package v1

import (
	json "encoding/json"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

// VolumeDeviceApplyConfiguration represents an declarative configuration of the VolumeDevice type for use
// with apply.
type VolumeDeviceApplyConfiguration struct {
	fields volumeDeviceFields
}

// VolumeDeviceApplyConfiguration constructs an declarative configuration of the VolumeDevice type for use with
// apply.
func VolumeDevice() *VolumeDeviceApplyConfiguration {
	return &VolumeDeviceApplyConfiguration{}
}

// volumeDeviceFields owns all fields except inlined fields.
// Inline fields are owned by their respective inline type in VolumeDeviceApplyConfiguration.
// They are copied to this type before marshalling, and are copied out
// after unmarshalling. The inlined types cannot be embedded because they do
// not expose their fields directly.
type volumeDeviceFields struct {
	Name       *string `json:"name,omitempty"`
	DevicePath *string `json:"devicePath,omitempty"`
}

// SetName sets the Name field in the declarative configuration to the given value.
func (b *VolumeDeviceApplyConfiguration) SetName(value string) *VolumeDeviceApplyConfiguration {
	b.fields.Name = &value
	return b
}

// RemoveName removes the Name field from the declarative configuration.
func (b *VolumeDeviceApplyConfiguration) RemoveName() *VolumeDeviceApplyConfiguration {
	b.fields.Name = nil
	return b
}

// GetName gets the Name field from the declarative configuration.
func (b *VolumeDeviceApplyConfiguration) GetName() (value string, ok bool) {
	if v := b.fields.Name; v != nil {
		return *v, true
	}
	return value, false
}

// SetDevicePath sets the DevicePath field in the declarative configuration to the given value.
func (b *VolumeDeviceApplyConfiguration) SetDevicePath(value string) *VolumeDeviceApplyConfiguration {
	b.fields.DevicePath = &value
	return b
}

// RemoveDevicePath removes the DevicePath field from the declarative configuration.
func (b *VolumeDeviceApplyConfiguration) RemoveDevicePath() *VolumeDeviceApplyConfiguration {
	b.fields.DevicePath = nil
	return b
}

// GetDevicePath gets the DevicePath field from the declarative configuration.
func (b *VolumeDeviceApplyConfiguration) GetDevicePath() (value string, ok bool) {
	if v := b.fields.DevicePath; v != nil {
		return *v, true
	}
	return value, false
}

// ToUnstructured converts VolumeDeviceApplyConfiguration to unstructured.
func (b *VolumeDeviceApplyConfiguration) ToUnstructured() interface{} {
	if b == nil {
		return nil
	}
	b.preMarshal()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(&b.fields)
	if err != nil {
		panic(err)
	}
	return u
}

// FromUnstructured converts unstructured to VolumeDeviceApplyConfiguration, replacing the contents
// of VolumeDeviceApplyConfiguration.
func (b *VolumeDeviceApplyConfiguration) FromUnstructured(u map[string]interface{}) error {
	m := &volumeDeviceFields{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u, m)
	if err != nil {
		return err
	}
	b.fields = *m
	b.postUnmarshal()
	return nil
}

// MarshalJSON marshals VolumeDeviceApplyConfiguration to JSON.
func (b *VolumeDeviceApplyConfiguration) MarshalJSON() ([]byte, error) {
	b.preMarshal()
	return json.Marshal(b.fields)
}

// UnmarshalJSON unmarshals JSON into VolumeDeviceApplyConfiguration, replacing the contents of
// VolumeDeviceApplyConfiguration.
func (b *VolumeDeviceApplyConfiguration) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &b.fields); err != nil {
		return err
	}
	b.postUnmarshal()
	return nil
}

// VolumeDeviceList represents a listAlias of VolumeDeviceApplyConfiguration.
type VolumeDeviceList []*VolumeDeviceApplyConfiguration

// VolumeDeviceList represents a map of VolumeDeviceApplyConfiguration.
type VolumeDeviceMap map[string]VolumeDeviceApplyConfiguration

func (b *VolumeDeviceApplyConfiguration) preMarshal() {
}
func (b *VolumeDeviceApplyConfiguration) postUnmarshal() {
}
