/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by typebuilder-gen. DO NOT EDIT.

package v1

import (
	json "encoding/json"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

// VolumeProjectionBuilder represents an declarative configuration of the VolumeProjection type for use
// with apply.
type VolumeProjectionBuilder struct {
	fields *volumeProjectionFields
}

// volumeProjectionFields is used by VolumeProjectionBuilder for json marshalling and unmarshalling.
// Is the source-of-truth for all fields except inlined fields.
// Inline fields are copied in from their builder type in VolumeProjectionBuilder before marshalling, and
// are copied out to the builder type in VolumeProjectionBuilder after unmarshalling.
// Inlined builder types cannot be embedded because they do not expose their fields directly.
type volumeProjectionFields struct {
	Secret              *SecretProjectionBuilder              `json:"secret,omitempty"`
	DownwardAPI         *DownwardAPIProjectionBuilder         `json:"downwardAPI,omitempty"`
	ConfigMap           *ConfigMapProjectionBuilder           `json:"configMap,omitempty"`
	ServiceAccountToken *ServiceAccountTokenProjectionBuilder `json:"serviceAccountToken,omitempty"`
}

func (b *VolumeProjectionBuilder) ensureInitialized() {
	if b.fields == nil {
		b.fields = &volumeProjectionFields{}
	}
}

// VolumeProjection constructs an declarative configuration of the VolumeProjection type for use with
// apply.
// Provided as a convenience.
func VolumeProjection() VolumeProjectionBuilder {
	return VolumeProjectionBuilder{fields: &volumeProjectionFields{}}
}

// SetSecret sets the Secret field in the declarative configuration to the given value.
func (b VolumeProjectionBuilder) SetSecret(value SecretProjectionBuilder) VolumeProjectionBuilder {
	b.ensureInitialized()
	b.fields.Secret = &value
	return b
}

// RemoveSecret removes the Secret field from the declarative configuration.
func (b VolumeProjectionBuilder) RemoveSecret() VolumeProjectionBuilder {
	b.ensureInitialized()
	b.fields.Secret = nil
	return b
}

// GetSecret gets the Secret field from the declarative configuration.
func (b VolumeProjectionBuilder) GetSecret() (value SecretProjectionBuilder, ok bool) {
	b.ensureInitialized()
	if v := b.fields.Secret; v != nil {
		return *v, true
	}
	return value, false
}

// SetDownwardAPI sets the DownwardAPI field in the declarative configuration to the given value.
func (b VolumeProjectionBuilder) SetDownwardAPI(value DownwardAPIProjectionBuilder) VolumeProjectionBuilder {
	b.ensureInitialized()
	b.fields.DownwardAPI = &value
	return b
}

// RemoveDownwardAPI removes the DownwardAPI field from the declarative configuration.
func (b VolumeProjectionBuilder) RemoveDownwardAPI() VolumeProjectionBuilder {
	b.ensureInitialized()
	b.fields.DownwardAPI = nil
	return b
}

// GetDownwardAPI gets the DownwardAPI field from the declarative configuration.
func (b VolumeProjectionBuilder) GetDownwardAPI() (value DownwardAPIProjectionBuilder, ok bool) {
	b.ensureInitialized()
	if v := b.fields.DownwardAPI; v != nil {
		return *v, true
	}
	return value, false
}

// SetConfigMap sets the ConfigMap field in the declarative configuration to the given value.
func (b VolumeProjectionBuilder) SetConfigMap(value ConfigMapProjectionBuilder) VolumeProjectionBuilder {
	b.ensureInitialized()
	b.fields.ConfigMap = &value
	return b
}

// RemoveConfigMap removes the ConfigMap field from the declarative configuration.
func (b VolumeProjectionBuilder) RemoveConfigMap() VolumeProjectionBuilder {
	b.ensureInitialized()
	b.fields.ConfigMap = nil
	return b
}

// GetConfigMap gets the ConfigMap field from the declarative configuration.
func (b VolumeProjectionBuilder) GetConfigMap() (value ConfigMapProjectionBuilder, ok bool) {
	b.ensureInitialized()
	if v := b.fields.ConfigMap; v != nil {
		return *v, true
	}
	return value, false
}

// SetServiceAccountToken sets the ServiceAccountToken field in the declarative configuration to the given value.
func (b VolumeProjectionBuilder) SetServiceAccountToken(value ServiceAccountTokenProjectionBuilder) VolumeProjectionBuilder {
	b.ensureInitialized()
	b.fields.ServiceAccountToken = &value
	return b
}

// RemoveServiceAccountToken removes the ServiceAccountToken field from the declarative configuration.
func (b VolumeProjectionBuilder) RemoveServiceAccountToken() VolumeProjectionBuilder {
	b.ensureInitialized()
	b.fields.ServiceAccountToken = nil
	return b
}

// GetServiceAccountToken gets the ServiceAccountToken field from the declarative configuration.
func (b VolumeProjectionBuilder) GetServiceAccountToken() (value ServiceAccountTokenProjectionBuilder, ok bool) {
	b.ensureInitialized()
	if v := b.fields.ServiceAccountToken; v != nil {
		return *v, true
	}
	return value, false
}

// ToUnstructured converts VolumeProjectionBuilder to unstructured.
func (b *VolumeProjectionBuilder) ToUnstructured() interface{} {
	if b == nil {
		return nil
	}
	b.ensureInitialized()
	b.preMarshal()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(b.fields)
	if err != nil {
		panic(err)
	}
	return u
}

// FromUnstructured converts unstructured to VolumeProjectionBuilder, replacing the contents
// of VolumeProjectionBuilder.
func (b *VolumeProjectionBuilder) FromUnstructured(u map[string]interface{}) error {
	m := &volumeProjectionFields{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u, m)
	if err != nil {
		return err
	}
	b.fields = m
	b.postUnmarshal()
	return nil
}

// MarshalJSON marshals VolumeProjectionBuilder to JSON.
func (b *VolumeProjectionBuilder) MarshalJSON() ([]byte, error) {
	b.ensureInitialized()
	b.preMarshal()
	return json.Marshal(b.fields)
}

// UnmarshalJSON unmarshals JSON into VolumeProjectionBuilder, replacing the contents of
// VolumeProjectionBuilder.
func (b *VolumeProjectionBuilder) UnmarshalJSON(data []byte) error {
	b.ensureInitialized()
	if err := json.Unmarshal(data, b.fields); err != nil {
		return err
	}
	b.postUnmarshal()
	return nil
}

// VolumeProjectionList represents a list of VolumeProjectionBuilder.
// Provided as a convenience.
type VolumeProjectionList []VolumeProjectionBuilder

// VolumeProjectionList represents a map of VolumeProjectionBuilder.
// Provided as a convenience.
type VolumeProjectionMap map[string]VolumeProjectionBuilder

func (b *VolumeProjectionBuilder) preMarshal() {
}
func (b *VolumeProjectionBuilder) postUnmarshal() {
}
