/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by typebuilder-gen. DO NOT EDIT.

package v1

import (
	json "encoding/json"

	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/client-go/typebuilders/meta/v1"
)

// DaemonSetBuilder represents an declarative configuration of the DaemonSet type for use
// with apply.
type DaemonSetBuilder struct {
	typeMeta v1.TypeMetaBuilder // inlined type
	fields   *daemonSetFields
}

// daemonSetFields is used by DaemonSetBuilder for json marshalling and unmarshalling.
// Is the source-of-truth for all fields except inlined fields.
// Inline fields are copied in from their builder type in DaemonSetBuilder before marshalling, and
// are copied out to the builder type in DaemonSetBuilder after unmarshalling.
// Inlined builder types cannot be embedded because they do not expose their fields directly.
type daemonSetFields struct {
	Kind       *string                 `json:"kind,omitempty"`       // inlined DaemonSetBuilder.typeMeta.Kind field
	APIVersion *string                 `json:"apiVersion,omitempty"` // inlined DaemonSetBuilder.typeMeta.APIVersion field
	ObjectMeta *v1.ObjectMetaBuilder   `json:"metadata,omitempty"`
	Spec       *DaemonSetSpecBuilder   `json:"spec,omitempty"`
	Status     *DaemonSetStatusBuilder `json:"status,omitempty"`
}

func (b *DaemonSetBuilder) ensureInitialized() {
	if b.fields == nil {
		b.fields = &daemonSetFields{}
	}
}

// DaemonSet constructs an declarative configuration of the DaemonSet type for use with
// apply.
// Provided as a convenience.
func DaemonSet() DaemonSetBuilder {
	return DaemonSetBuilder{fields: &daemonSetFields{}}
}

// SetTypeMeta sets the TypeMeta field in the declarative configuration to the given value.
func (b DaemonSetBuilder) SetTypeMeta(value v1.TypeMetaBuilder) DaemonSetBuilder {
	b.ensureInitialized()
	b.typeMeta = value
	return b
}

// RemoveTypeMeta removes the TypeMeta field from the declarative configuration.
func (b DaemonSetBuilder) RemoveTypeMeta() DaemonSetBuilder {
	b.ensureInitialized()
	b.typeMeta = v1.TypeMetaBuilder{}
	return b
}

// GetTypeMeta gets the TypeMeta field from the declarative configuration.
func (b DaemonSetBuilder) GetTypeMeta() (value v1.TypeMetaBuilder, ok bool) {
	b.ensureInitialized()
	return b.typeMeta, true
}

// SetObjectMeta sets the ObjectMeta field in the declarative configuration to the given value.
func (b DaemonSetBuilder) SetObjectMeta(value v1.ObjectMetaBuilder) DaemonSetBuilder {
	b.ensureInitialized()
	b.fields.ObjectMeta = &value
	return b
}

// RemoveObjectMeta removes the ObjectMeta field from the declarative configuration.
func (b DaemonSetBuilder) RemoveObjectMeta() DaemonSetBuilder {
	b.ensureInitialized()
	b.fields.ObjectMeta = nil
	return b
}

// GetObjectMeta gets the ObjectMeta field from the declarative configuration.
func (b DaemonSetBuilder) GetObjectMeta() (value v1.ObjectMetaBuilder, ok bool) {
	b.ensureInitialized()
	if v := b.fields.ObjectMeta; v != nil {
		return *v, true
	}
	return value, false
}

// SetSpec sets the Spec field in the declarative configuration to the given value.
func (b DaemonSetBuilder) SetSpec(value DaemonSetSpecBuilder) DaemonSetBuilder {
	b.ensureInitialized()
	b.fields.Spec = &value
	return b
}

// RemoveSpec removes the Spec field from the declarative configuration.
func (b DaemonSetBuilder) RemoveSpec() DaemonSetBuilder {
	b.ensureInitialized()
	b.fields.Spec = nil
	return b
}

// GetSpec gets the Spec field from the declarative configuration.
func (b DaemonSetBuilder) GetSpec() (value DaemonSetSpecBuilder, ok bool) {
	b.ensureInitialized()
	if v := b.fields.Spec; v != nil {
		return *v, true
	}
	return value, false
}

// SetStatus sets the Status field in the declarative configuration to the given value.
func (b DaemonSetBuilder) SetStatus(value DaemonSetStatusBuilder) DaemonSetBuilder {
	b.ensureInitialized()
	b.fields.Status = &value
	return b
}

// RemoveStatus removes the Status field from the declarative configuration.
func (b DaemonSetBuilder) RemoveStatus() DaemonSetBuilder {
	b.ensureInitialized()
	b.fields.Status = nil
	return b
}

// GetStatus gets the Status field from the declarative configuration.
func (b DaemonSetBuilder) GetStatus() (value DaemonSetStatusBuilder, ok bool) {
	b.ensureInitialized()
	if v := b.fields.Status; v != nil {
		return *v, true
	}
	return value, false
}

// ToUnstructured converts DaemonSetBuilder to unstructured.
func (b *DaemonSetBuilder) ToUnstructured() interface{} {
	if b == nil {
		return nil
	}
	b.ensureInitialized()
	b.preMarshal()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(b.fields)
	if err != nil {
		panic(err)
	}
	return u
}

// FromUnstructured converts unstructured to DaemonSetBuilder, replacing the contents
// of DaemonSetBuilder.
func (b *DaemonSetBuilder) FromUnstructured(u map[string]interface{}) error {
	m := &daemonSetFields{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u, m)
	if err != nil {
		return err
	}
	b.fields = m
	b.postUnmarshal()
	return nil
}

// MarshalJSON marshals DaemonSetBuilder to JSON.
func (b *DaemonSetBuilder) MarshalJSON() ([]byte, error) {
	u := &unstructured.Unstructured{Object: b.ToUnstructured().(map[string]interface{})}
	return u.MarshalJSON()
}

// UnmarshalJSON unmarshals JSON into DaemonSetBuilder, replacing the contents of
// DaemonSetBuilder.
func (b *DaemonSetBuilder) UnmarshalJSON(data []byte) error {
	b.ensureInitialized()
	if err := json.Unmarshal(data, b.fields); err != nil {
		return err
	}
	b.postUnmarshal()
	return nil
}

// DaemonSetList represents a list of DaemonSetBuilder.
// Provided as a convenience.
type DaemonSetList []DaemonSetBuilder

// DaemonSetList represents a map of DaemonSetBuilder.
// Provided as a convenience.
type DaemonSetMap map[string]DaemonSetBuilder

func (b *DaemonSetBuilder) preMarshal() {
	if v, ok := b.typeMeta.GetKind(); ok {
		b.fields.Kind = &v
	}
	if v, ok := b.typeMeta.GetAPIVersion(); ok {
		b.fields.APIVersion = &v
	}
}
func (b *DaemonSetBuilder) postUnmarshal() {
	if b.fields.Kind != nil {
		b.typeMeta.SetKind(*b.fields.Kind)
	}
	if b.fields.APIVersion != nil {
		b.typeMeta.SetAPIVersion(*b.fields.APIVersion)
	}
}
