/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by typebuilder-gen. DO NOT EDIT.

package v1

import (
	json "encoding/json"

	runtime "k8s.io/apimachinery/pkg/runtime"
	corev1 "k8s.io/client-go/typebuilders/core/v1"
	v1 "k8s.io/client-go/typebuilders/meta/v1"
)

// DeploymentSpecBuilder represents an declarative configuration of the DeploymentSpec type for use
// with apply.
type DeploymentSpecBuilder struct {
	fields deploymentSpecFields
}

// deploymentSpecFields owns all fields except inlined fields.
// Inline fields are owned by their respective inline type in DeploymentSpecBuilder.
// They are copied to this type before marshalling, and are copied out
// after unmarshalling. The inlined types cannot be embedded because they do
// not expose their fields directly.
type deploymentSpecFields struct {
	Replicas                *int32                         `json:"replicas,omitempty"`
	Selector                *v1.LabelSelectorBuilder       `json:"selector,omitempty"`
	Template                *corev1.PodTemplateSpecBuilder `json:"template,omitempty"`
	Strategy                *DeploymentStrategyBuilder     `json:"strategy,omitempty"`
	MinReadySeconds         *int32                         `json:"minReadySeconds,omitempty"`
	RevisionHistoryLimit    *int32                         `json:"revisionHistoryLimit,omitempty"`
	Paused                  *bool                          `json:"paused,omitempty"`
	ProgressDeadlineSeconds *int32                         `json:"progressDeadlineSeconds,omitempty"`
}

// DeploymentSpec constructs an declarative configuration of the DeploymentSpec type for use with
// apply.
func DeploymentSpec() *DeploymentSpecBuilder {
	return &DeploymentSpecBuilder{}
}

// SetReplicas sets the Replicas field in the declarative configuration to the given value.
func (b *DeploymentSpecBuilder) SetReplicas(value int32) *DeploymentSpecBuilder {
	b.fields.Replicas = &value
	return b
}

// RemoveReplicas removes the Replicas field from the declarative configuration.
func (b *DeploymentSpecBuilder) RemoveReplicas() *DeploymentSpecBuilder {
	b.fields.Replicas = nil
	return b
}

// GetReplicas gets the Replicas field from the declarative configuration.
func (b *DeploymentSpecBuilder) GetReplicas() (value int32, ok bool) {
	if v := b.fields.Replicas; v != nil {
		return *v, true
	}
	return value, false
}

// SetSelector sets the Selector field in the declarative configuration to the given value.
func (b *DeploymentSpecBuilder) SetSelector(value *v1.LabelSelectorBuilder) *DeploymentSpecBuilder {
	b.fields.Selector = value
	return b
}

// RemoveSelector removes the Selector field from the declarative configuration.
func (b *DeploymentSpecBuilder) RemoveSelector() *DeploymentSpecBuilder {
	b.fields.Selector = nil
	return b
}

// GetSelector gets the Selector field from the declarative configuration.
func (b *DeploymentSpecBuilder) GetSelector() (value *v1.LabelSelectorBuilder, ok bool) {
	return b.fields.Selector, b.fields.Selector != nil
}

// SetTemplate sets the Template field in the declarative configuration to the given value.
func (b *DeploymentSpecBuilder) SetTemplate(value *corev1.PodTemplateSpecBuilder) *DeploymentSpecBuilder {
	b.fields.Template = value
	return b
}

// RemoveTemplate removes the Template field from the declarative configuration.
func (b *DeploymentSpecBuilder) RemoveTemplate() *DeploymentSpecBuilder {
	b.fields.Template = nil
	return b
}

// GetTemplate gets the Template field from the declarative configuration.
func (b *DeploymentSpecBuilder) GetTemplate() (value *corev1.PodTemplateSpecBuilder, ok bool) {
	return b.fields.Template, b.fields.Template != nil
}

// SetStrategy sets the Strategy field in the declarative configuration to the given value.
func (b *DeploymentSpecBuilder) SetStrategy(value *DeploymentStrategyBuilder) *DeploymentSpecBuilder {
	b.fields.Strategy = value
	return b
}

// RemoveStrategy removes the Strategy field from the declarative configuration.
func (b *DeploymentSpecBuilder) RemoveStrategy() *DeploymentSpecBuilder {
	b.fields.Strategy = nil
	return b
}

// GetStrategy gets the Strategy field from the declarative configuration.
func (b *DeploymentSpecBuilder) GetStrategy() (value *DeploymentStrategyBuilder, ok bool) {
	return b.fields.Strategy, b.fields.Strategy != nil
}

// SetMinReadySeconds sets the MinReadySeconds field in the declarative configuration to the given value.
func (b *DeploymentSpecBuilder) SetMinReadySeconds(value int32) *DeploymentSpecBuilder {
	b.fields.MinReadySeconds = &value
	return b
}

// RemoveMinReadySeconds removes the MinReadySeconds field from the declarative configuration.
func (b *DeploymentSpecBuilder) RemoveMinReadySeconds() *DeploymentSpecBuilder {
	b.fields.MinReadySeconds = nil
	return b
}

// GetMinReadySeconds gets the MinReadySeconds field from the declarative configuration.
func (b *DeploymentSpecBuilder) GetMinReadySeconds() (value int32, ok bool) {
	if v := b.fields.MinReadySeconds; v != nil {
		return *v, true
	}
	return value, false
}

// SetRevisionHistoryLimit sets the RevisionHistoryLimit field in the declarative configuration to the given value.
func (b *DeploymentSpecBuilder) SetRevisionHistoryLimit(value int32) *DeploymentSpecBuilder {
	b.fields.RevisionHistoryLimit = &value
	return b
}

// RemoveRevisionHistoryLimit removes the RevisionHistoryLimit field from the declarative configuration.
func (b *DeploymentSpecBuilder) RemoveRevisionHistoryLimit() *DeploymentSpecBuilder {
	b.fields.RevisionHistoryLimit = nil
	return b
}

// GetRevisionHistoryLimit gets the RevisionHistoryLimit field from the declarative configuration.
func (b *DeploymentSpecBuilder) GetRevisionHistoryLimit() (value int32, ok bool) {
	if v := b.fields.RevisionHistoryLimit; v != nil {
		return *v, true
	}
	return value, false
}

// SetPaused sets the Paused field in the declarative configuration to the given value.
func (b *DeploymentSpecBuilder) SetPaused(value bool) *DeploymentSpecBuilder {
	b.fields.Paused = &value
	return b
}

// RemovePaused removes the Paused field from the declarative configuration.
func (b *DeploymentSpecBuilder) RemovePaused() *DeploymentSpecBuilder {
	b.fields.Paused = nil
	return b
}

// GetPaused gets the Paused field from the declarative configuration.
func (b *DeploymentSpecBuilder) GetPaused() (value bool, ok bool) {
	if v := b.fields.Paused; v != nil {
		return *v, true
	}
	return value, false
}

// SetProgressDeadlineSeconds sets the ProgressDeadlineSeconds field in the declarative configuration to the given value.
func (b *DeploymentSpecBuilder) SetProgressDeadlineSeconds(value int32) *DeploymentSpecBuilder {
	b.fields.ProgressDeadlineSeconds = &value
	return b
}

// RemoveProgressDeadlineSeconds removes the ProgressDeadlineSeconds field from the declarative configuration.
func (b *DeploymentSpecBuilder) RemoveProgressDeadlineSeconds() *DeploymentSpecBuilder {
	b.fields.ProgressDeadlineSeconds = nil
	return b
}

// GetProgressDeadlineSeconds gets the ProgressDeadlineSeconds field from the declarative configuration.
func (b *DeploymentSpecBuilder) GetProgressDeadlineSeconds() (value int32, ok bool) {
	if v := b.fields.ProgressDeadlineSeconds; v != nil {
		return *v, true
	}
	return value, false
}

// ToUnstructured converts DeploymentSpecBuilder to unstructured.
func (b *DeploymentSpecBuilder) ToUnstructured() interface{} {
	if b == nil {
		return nil
	}
	b.preMarshal()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(&b.fields)
	if err != nil {
		panic(err)
	}
	return u
}

// FromUnstructured converts unstructured to DeploymentSpecBuilder, replacing the contents
// of DeploymentSpecBuilder.
func (b *DeploymentSpecBuilder) FromUnstructured(u map[string]interface{}) error {
	m := &deploymentSpecFields{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u, m)
	if err != nil {
		return err
	}
	b.fields = *m
	b.postUnmarshal()
	return nil
}

// MarshalJSON marshals DeploymentSpecBuilder to JSON.
func (b *DeploymentSpecBuilder) MarshalJSON() ([]byte, error) {
	b.preMarshal()
	return json.Marshal(b.fields)
}

// UnmarshalJSON unmarshals JSON into DeploymentSpecBuilder, replacing the contents of
// DeploymentSpecBuilder.
func (b *DeploymentSpecBuilder) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &b.fields); err != nil {
		return err
	}
	b.postUnmarshal()
	return nil
}

// DeploymentSpecList represents a list of DeploymentSpecBuilder.
type DeploymentSpecList []*DeploymentSpecBuilder

// DeploymentSpecList represents a map of DeploymentSpecBuilder.
type DeploymentSpecMap map[string]DeploymentSpecBuilder

func (b *DeploymentSpecBuilder) preMarshal() {
}
func (b *DeploymentSpecBuilder) postUnmarshal() {
}
