/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by typebuilder-gen. DO NOT EDIT.

package v1beta2

import (
	json "encoding/json"

	v1beta2 "k8s.io/api/apps/v1beta2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DaemonSetUpdateStrategyApplyConfiguration represents an declarative configuration of the DaemonSetUpdateStrategy type for use
// with apply.
type DaemonSetUpdateStrategyApplyConfiguration struct {
	fields daemonSetUpdateStrategyFields
}

// DaemonSetUpdateStrategyApplyConfiguration constructs an declarative configuration of the DaemonSetUpdateStrategy type for use with
// apply.
func DaemonSetUpdateStrategy() *DaemonSetUpdateStrategyApplyConfiguration {
	return &DaemonSetUpdateStrategyApplyConfiguration{}
}

// daemonSetUpdateStrategyFields owns all fields except inlined fields.
// Inline fields are owned by their respective inline type in DaemonSetUpdateStrategyApplyConfiguration.
// They are copied to this type before marshalling, and are copied out
// after unmarshalling. The inlined types cannot be embedded because they do
// not expose their fields directly.
type daemonSetUpdateStrategyFields struct {
	Type          *v1beta2.DaemonSetUpdateStrategyType      `json:"type,omitempty"`
	RollingUpdate *RollingUpdateDaemonSetApplyConfiguration `json:"rollingUpdate,omitempty"`
}

// SetType sets the Type field in the declarative configuration to the given value.
func (b *DaemonSetUpdateStrategyApplyConfiguration) SetType(value v1beta2.DaemonSetUpdateStrategyType) *DaemonSetUpdateStrategyApplyConfiguration {
	b.fields.Type = &value
	return b
}

// RemoveType removes the Type field from the declarative configuration.
func (b *DaemonSetUpdateStrategyApplyConfiguration) RemoveType() *DaemonSetUpdateStrategyApplyConfiguration {
	b.fields.Type = nil
	return b
}

// GetType gets the Type field from the declarative configuration.
func (b *DaemonSetUpdateStrategyApplyConfiguration) GetType() (value v1beta2.DaemonSetUpdateStrategyType, ok bool) {
	if v := b.fields.Type; v != nil {
		return *v, true
	}
	return value, false
}

// SetRollingUpdate sets the RollingUpdate field in the declarative configuration to the given value.
func (b *DaemonSetUpdateStrategyApplyConfiguration) SetRollingUpdate(value *RollingUpdateDaemonSetApplyConfiguration) *DaemonSetUpdateStrategyApplyConfiguration {
	b.fields.RollingUpdate = value
	return b
}

// RemoveRollingUpdate removes the RollingUpdate field from the declarative configuration.
func (b *DaemonSetUpdateStrategyApplyConfiguration) RemoveRollingUpdate() *DaemonSetUpdateStrategyApplyConfiguration {
	b.fields.RollingUpdate = nil
	return b
}

// GetRollingUpdate gets the RollingUpdate field from the declarative configuration.
func (b *DaemonSetUpdateStrategyApplyConfiguration) GetRollingUpdate() (value *RollingUpdateDaemonSetApplyConfiguration, ok bool) {
	return b.fields.RollingUpdate, b.fields.RollingUpdate != nil
}

// ToUnstructured converts DaemonSetUpdateStrategyApplyConfiguration to unstructured.
func (b *DaemonSetUpdateStrategyApplyConfiguration) ToUnstructured() interface{} {
	if b == nil {
		return nil
	}
	b.preMarshal()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(&b.fields)
	if err != nil {
		panic(err)
	}
	return u
}

// FromUnstructured converts unstructured to DaemonSetUpdateStrategyApplyConfiguration, replacing the contents
// of DaemonSetUpdateStrategyApplyConfiguration.
func (b *DaemonSetUpdateStrategyApplyConfiguration) FromUnstructured(u map[string]interface{}) error {
	m := &daemonSetUpdateStrategyFields{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u, m)
	if err != nil {
		return err
	}
	b.fields = *m
	b.postUnmarshal()
	return nil
}

// MarshalJSON marshals DaemonSetUpdateStrategyApplyConfiguration to JSON.
func (b *DaemonSetUpdateStrategyApplyConfiguration) MarshalJSON() ([]byte, error) {
	b.preMarshal()
	return json.Marshal(b.fields)
}

// UnmarshalJSON unmarshals JSON into DaemonSetUpdateStrategyApplyConfiguration, replacing the contents of
// DaemonSetUpdateStrategyApplyConfiguration.
func (b *DaemonSetUpdateStrategyApplyConfiguration) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &b.fields); err != nil {
		return err
	}
	b.postUnmarshal()
	return nil
}

// DaemonSetUpdateStrategyList represents a listAlias of DaemonSetUpdateStrategyApplyConfiguration.
type DaemonSetUpdateStrategyList []*DaemonSetUpdateStrategyApplyConfiguration

// DaemonSetUpdateStrategyList represents a map of DaemonSetUpdateStrategyApplyConfiguration.
type DaemonSetUpdateStrategyMap map[string]DaemonSetUpdateStrategyApplyConfiguration

func (b *DaemonSetUpdateStrategyApplyConfiguration) preMarshal() {
}
func (b *DaemonSetUpdateStrategyApplyConfiguration) postUnmarshal() {
}
