/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by typebuilder-gen. DO NOT EDIT.

package v1beta1

import (
	json "encoding/json"

	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/client-go/typebuilders/meta/v1"
)

// ControllerRevisionApplyConfiguration represents an declarative configuration of the ControllerRevision type for use
// with apply.
type ControllerRevisionApplyConfiguration struct {
	typeMeta *v1.TypeMetaApplyConfiguration // inlined type
	fields   controllerRevisionFields
}

// ControllerRevisionApplyConfiguration constructs an declarative configuration of the ControllerRevision type for use with
// apply.
func ControllerRevision() *ControllerRevisionApplyConfiguration {
	return &ControllerRevisionApplyConfiguration{}
}

// controllerRevisionFields owns all fields except inlined fields.
// Inline fields are owned by their respective inline type in ControllerRevisionApplyConfiguration.
// They are copied to this type before marshalling, and are copied out
// after unmarshalling. The inlined types cannot be embedded because they do
// not expose their fields directly.
type controllerRevisionFields struct {
	Kind       *string                          `json:"kind,omitempty"`       // inlined ControllerRevisionApplyConfiguration.typeMeta.Kind field
	APIVersion *string                          `json:"apiVersion,omitempty"` // inlined ControllerRevisionApplyConfiguration.typeMeta.APIVersion field
	ObjectMeta *v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	Data       *runtime.RawExtension            `json:"data,omitempty"`
	Revision   *int64                           `json:"revision,omitempty"`
}

// SetTypeMeta sets the TypeMeta field in the declarative configuration to the given value.
func (b *ControllerRevisionApplyConfiguration) SetTypeMeta(value *v1.TypeMetaApplyConfiguration) *ControllerRevisionApplyConfiguration {
	b.typeMeta = value
	return b
}

// RemoveTypeMeta removes the TypeMeta field from the declarative configuration.
func (b *ControllerRevisionApplyConfiguration) RemoveTypeMeta() *ControllerRevisionApplyConfiguration {
	b.typeMeta = nil
	return b
}

// GetTypeMeta gets the TypeMeta field from the declarative configuration.
func (b *ControllerRevisionApplyConfiguration) GetTypeMeta() (value *v1.TypeMetaApplyConfiguration, ok bool) {
	return b.typeMeta, true
}

// SetObjectMeta sets the ObjectMeta field in the declarative configuration to the given value.
func (b *ControllerRevisionApplyConfiguration) SetObjectMeta(value *v1.ObjectMetaApplyConfiguration) *ControllerRevisionApplyConfiguration {
	b.fields.ObjectMeta = value
	return b
}

// RemoveObjectMeta removes the ObjectMeta field from the declarative configuration.
func (b *ControllerRevisionApplyConfiguration) RemoveObjectMeta() *ControllerRevisionApplyConfiguration {
	b.fields.ObjectMeta = nil
	return b
}

// GetObjectMeta gets the ObjectMeta field from the declarative configuration.
func (b *ControllerRevisionApplyConfiguration) GetObjectMeta() (value *v1.ObjectMetaApplyConfiguration, ok bool) {
	return b.fields.ObjectMeta, b.fields.ObjectMeta != nil
}

// SetData sets the Data field in the declarative configuration to the given value.
func (b *ControllerRevisionApplyConfiguration) SetData(value runtime.RawExtension) *ControllerRevisionApplyConfiguration {
	b.fields.Data = &value
	return b
}

// RemoveData removes the Data field from the declarative configuration.
func (b *ControllerRevisionApplyConfiguration) RemoveData() *ControllerRevisionApplyConfiguration {
	b.fields.Data = nil
	return b
}

// GetData gets the Data field from the declarative configuration.
func (b *ControllerRevisionApplyConfiguration) GetData() (value runtime.RawExtension, ok bool) {
	if v := b.fields.Data; v != nil {
		return *v, true
	}
	return value, false
}

// SetRevision sets the Revision field in the declarative configuration to the given value.
func (b *ControllerRevisionApplyConfiguration) SetRevision(value int64) *ControllerRevisionApplyConfiguration {
	b.fields.Revision = &value
	return b
}

// RemoveRevision removes the Revision field from the declarative configuration.
func (b *ControllerRevisionApplyConfiguration) RemoveRevision() *ControllerRevisionApplyConfiguration {
	b.fields.Revision = nil
	return b
}

// GetRevision gets the Revision field from the declarative configuration.
func (b *ControllerRevisionApplyConfiguration) GetRevision() (value int64, ok bool) {
	if v := b.fields.Revision; v != nil {
		return *v, true
	}
	return value, false
}

// ToUnstructured converts ControllerRevisionApplyConfiguration to unstructured.
func (b *ControllerRevisionApplyConfiguration) ToUnstructured() interface{} {
	if b == nil {
		return nil
	}
	b.preMarshal()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(&b.fields)
	if err != nil {
		panic(err)
	}
	return u
}

// FromUnstructured converts unstructured to ControllerRevisionApplyConfiguration, replacing the contents
// of ControllerRevisionApplyConfiguration.
func (b *ControllerRevisionApplyConfiguration) FromUnstructured(u map[string]interface{}) error {
	m := &controllerRevisionFields{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u, m)
	if err != nil {
		return err
	}
	b.fields = *m
	b.postUnmarshal()
	return nil
}

// MarshalJSON marshals ControllerRevisionApplyConfiguration to JSON.
func (b *ControllerRevisionApplyConfiguration) MarshalJSON() ([]byte, error) {
	b.preMarshal()
	return json.Marshal(b.fields)
}

// UnmarshalJSON unmarshals JSON into ControllerRevisionApplyConfiguration, replacing the contents of
// ControllerRevisionApplyConfiguration.
func (b *ControllerRevisionApplyConfiguration) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &b.fields); err != nil {
		return err
	}
	b.postUnmarshal()
	return nil
}

// ControllerRevisionList represents a listAlias of ControllerRevisionApplyConfiguration.
type ControllerRevisionList []*ControllerRevisionApplyConfiguration

// ControllerRevisionList represents a map of ControllerRevisionApplyConfiguration.
type ControllerRevisionMap map[string]ControllerRevisionApplyConfiguration

func (b *ControllerRevisionApplyConfiguration) preMarshal() {
	if b.typeMeta != nil {
		if v, ok := b.typeMeta.GetKind(); ok {
			b.fields.Kind = &v
		}
		if v, ok := b.typeMeta.GetAPIVersion(); ok {
			b.fields.APIVersion = &v
		}
	}
}
func (b *ControllerRevisionApplyConfiguration) postUnmarshal() {
	if b.typeMeta == nil {
		b.typeMeta = &v1.TypeMetaApplyConfiguration{}
	}
	if b.fields.Kind != nil {
		b.typeMeta.SetKind(*b.fields.Kind)
	}
	if b.fields.APIVersion != nil {
		b.typeMeta.SetAPIVersion(*b.fields.APIVersion)
	}
}
