/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PodDisruptionBudgetStatusApplyConfiguration represents an declarative configuration of the PodDisruptionBudgetStatus type for use
// with apply.
type PodDisruptionBudgetStatusApplyConfiguration struct {
	ObservedGeneration *int64              `json:"observedGeneration,omitempty"`
	DisruptedPods      *map[string]v1.Time `json:"disruptedPods,omitempty"`
	DisruptionsAllowed *int32              `json:"disruptionsAllowed,omitempty"`
	CurrentHealthy     *int32              `json:"currentHealthy,omitempty"`
	DesiredHealthy     *int32              `json:"desiredHealthy,omitempty"`
	ExpectedPods       *int32              `json:"expectedPods,omitempty"`
}

// PodDisruptionBudgetStatusApplyConfiguration constructs an declarative configuration of the PodDisruptionBudgetStatus type for use with
// apply.
func PodDisruptionBudgetStatus() *PodDisruptionBudgetStatusApplyConfiguration {
	return &PodDisruptionBudgetStatusApplyConfiguration{}
}

// SetObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value.
func (b *PodDisruptionBudgetStatusApplyConfiguration) SetObservedGeneration(value int64) *PodDisruptionBudgetStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// SetDisruptedPods sets the DisruptedPods field in the declarative configuration to the given value.
func (b *PodDisruptionBudgetStatusApplyConfiguration) SetDisruptedPods(value map[string]v1.Time) *PodDisruptionBudgetStatusApplyConfiguration {
	b.DisruptedPods = &value
	return b
}

// SetDisruptionsAllowed sets the DisruptionsAllowed field in the declarative configuration to the given value.
func (b *PodDisruptionBudgetStatusApplyConfiguration) SetDisruptionsAllowed(value int32) *PodDisruptionBudgetStatusApplyConfiguration {
	b.DisruptionsAllowed = &value
	return b
}

// SetCurrentHealthy sets the CurrentHealthy field in the declarative configuration to the given value.
func (b *PodDisruptionBudgetStatusApplyConfiguration) SetCurrentHealthy(value int32) *PodDisruptionBudgetStatusApplyConfiguration {
	b.CurrentHealthy = &value
	return b
}

// SetDesiredHealthy sets the DesiredHealthy field in the declarative configuration to the given value.
func (b *PodDisruptionBudgetStatusApplyConfiguration) SetDesiredHealthy(value int32) *PodDisruptionBudgetStatusApplyConfiguration {
	b.DesiredHealthy = &value
	return b
}

// SetExpectedPods sets the ExpectedPods field in the declarative configuration to the given value.
func (b *PodDisruptionBudgetStatusApplyConfiguration) SetExpectedPods(value int32) *PodDisruptionBudgetStatusApplyConfiguration {
	b.ExpectedPods = &value
	return b
}
