/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by typebuilder-gen. DO NOT EDIT.

package v1beta1

import (
	json "encoding/json"

	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/client-go/typebuilders/meta/v1"
)

// TokenReviewApplyConfiguration represents an declarative configuration of the TokenReview type for use
// with apply.
type TokenReviewApplyConfiguration struct {
	typeMeta *v1.TypeMetaApplyConfiguration // inlined type
	fields   tokenReviewFields
}

// TokenReviewApplyConfiguration constructs an declarative configuration of the TokenReview type for use with
// apply.
func TokenReview() *TokenReviewApplyConfiguration {
	return &TokenReviewApplyConfiguration{}
}

// tokenReviewFields owns all fields except inlined fields.
// Inline fields are owned by their respective inline type in TokenReviewApplyConfiguration.
// They are copied to this type before marshalling, and are copied out
// after unmarshalling. The inlined types cannot be embedded because they do
// not expose their fields directly.
type tokenReviewFields struct {
	Kind       *string                              `json:"kind,omitempty"`       // inlined TokenReviewApplyConfiguration.typeMeta.Kind field
	APIVersion *string                              `json:"apiVersion,omitempty"` // inlined TokenReviewApplyConfiguration.typeMeta.APIVersion field
	ObjectMeta *v1.ObjectMetaApplyConfiguration     `json:"metadata,omitempty"`
	Spec       *TokenReviewSpecApplyConfiguration   `json:"spec,omitempty"`
	Status     *TokenReviewStatusApplyConfiguration `json:"status,omitempty"`
}

// SetTypeMeta sets the TypeMeta field in the declarative configuration to the given value.
func (b *TokenReviewApplyConfiguration) SetTypeMeta(value *v1.TypeMetaApplyConfiguration) *TokenReviewApplyConfiguration {
	b.typeMeta = value
	return b
}

// RemoveTypeMeta removes the TypeMeta field from the declarative configuration.
func (b *TokenReviewApplyConfiguration) RemoveTypeMeta() *TokenReviewApplyConfiguration {
	b.typeMeta = nil
	return b
}

// GetTypeMeta gets the TypeMeta field from the declarative configuration.
func (b *TokenReviewApplyConfiguration) GetTypeMeta() (value *v1.TypeMetaApplyConfiguration, ok bool) {
	return b.typeMeta, true
}

// SetObjectMeta sets the ObjectMeta field in the declarative configuration to the given value.
func (b *TokenReviewApplyConfiguration) SetObjectMeta(value *v1.ObjectMetaApplyConfiguration) *TokenReviewApplyConfiguration {
	b.fields.ObjectMeta = value
	return b
}

// RemoveObjectMeta removes the ObjectMeta field from the declarative configuration.
func (b *TokenReviewApplyConfiguration) RemoveObjectMeta() *TokenReviewApplyConfiguration {
	b.fields.ObjectMeta = nil
	return b
}

// GetObjectMeta gets the ObjectMeta field from the declarative configuration.
func (b *TokenReviewApplyConfiguration) GetObjectMeta() (value *v1.ObjectMetaApplyConfiguration, ok bool) {
	return b.fields.ObjectMeta, b.fields.ObjectMeta != nil
}

// SetSpec sets the Spec field in the declarative configuration to the given value.
func (b *TokenReviewApplyConfiguration) SetSpec(value *TokenReviewSpecApplyConfiguration) *TokenReviewApplyConfiguration {
	b.fields.Spec = value
	return b
}

// RemoveSpec removes the Spec field from the declarative configuration.
func (b *TokenReviewApplyConfiguration) RemoveSpec() *TokenReviewApplyConfiguration {
	b.fields.Spec = nil
	return b
}

// GetSpec gets the Spec field from the declarative configuration.
func (b *TokenReviewApplyConfiguration) GetSpec() (value *TokenReviewSpecApplyConfiguration, ok bool) {
	return b.fields.Spec, b.fields.Spec != nil
}

// SetStatus sets the Status field in the declarative configuration to the given value.
func (b *TokenReviewApplyConfiguration) SetStatus(value *TokenReviewStatusApplyConfiguration) *TokenReviewApplyConfiguration {
	b.fields.Status = value
	return b
}

// RemoveStatus removes the Status field from the declarative configuration.
func (b *TokenReviewApplyConfiguration) RemoveStatus() *TokenReviewApplyConfiguration {
	b.fields.Status = nil
	return b
}

// GetStatus gets the Status field from the declarative configuration.
func (b *TokenReviewApplyConfiguration) GetStatus() (value *TokenReviewStatusApplyConfiguration, ok bool) {
	return b.fields.Status, b.fields.Status != nil
}

// ToUnstructured converts TokenReviewApplyConfiguration to unstructured.
func (b *TokenReviewApplyConfiguration) ToUnstructured() interface{} {
	if b == nil {
		return nil
	}
	b.preMarshal()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(&b.fields)
	if err != nil {
		panic(err)
	}
	return u
}

// FromUnstructured converts unstructured to TokenReviewApplyConfiguration, replacing the contents
// of TokenReviewApplyConfiguration.
func (b *TokenReviewApplyConfiguration) FromUnstructured(u map[string]interface{}) error {
	m := &tokenReviewFields{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u, m)
	if err != nil {
		return err
	}
	b.fields = *m
	b.postUnmarshal()
	return nil
}

// MarshalJSON marshals TokenReviewApplyConfiguration to JSON.
func (b *TokenReviewApplyConfiguration) MarshalJSON() ([]byte, error) {
	b.preMarshal()
	return json.Marshal(b.fields)
}

// UnmarshalJSON unmarshals JSON into TokenReviewApplyConfiguration, replacing the contents of
// TokenReviewApplyConfiguration.
func (b *TokenReviewApplyConfiguration) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &b.fields); err != nil {
		return err
	}
	b.postUnmarshal()
	return nil
}

// TokenReviewList represents a listAlias of TokenReviewApplyConfiguration.
type TokenReviewList []*TokenReviewApplyConfiguration

// TokenReviewList represents a map of TokenReviewApplyConfiguration.
type TokenReviewMap map[string]TokenReviewApplyConfiguration

func (b *TokenReviewApplyConfiguration) preMarshal() {
	if b.typeMeta != nil {
		if v, ok := b.typeMeta.GetKind(); ok {
			b.fields.Kind = &v
		}
		if v, ok := b.typeMeta.GetAPIVersion(); ok {
			b.fields.APIVersion = &v
		}
	}
}
func (b *TokenReviewApplyConfiguration) postUnmarshal() {
	if b.typeMeta == nil {
		b.typeMeta = &v1.TypeMetaApplyConfiguration{}
	}
	if b.fields.Kind != nil {
		b.typeMeta.SetKind(*b.fields.Kind)
	}
	if b.fields.APIVersion != nil {
		b.typeMeta.SetAPIVersion(*b.fields.APIVersion)
	}
}
