/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	json "encoding/json"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

// StatefulSetStatusApplyConfiguration represents an declarative configuration of the StatefulSetStatus type for use
// with apply.
type StatefulSetStatusApplyConfiguration struct {
	fields statefulSetStatusFields
}

// StatefulSetStatusApplyConfiguration constructs an declarative configuration of the StatefulSetStatus type for use with
// apply.
func StatefulSetStatus() *StatefulSetStatusApplyConfiguration {
	return &StatefulSetStatusApplyConfiguration{}
}

// statefulSetStatusFields owns all fields except inlined fields.
// Inline fields are owned by their respective inline type in StatefulSetStatusApplyConfiguration.
// They are copied to this type before marshalling, and are copied out
// after unmarshalling. The inlined types cannot be embedded because they do
// not expose their fields directly.
type statefulSetStatusFields struct {
	ObservedGeneration *int64                    `json:"observedGeneration,omitempty"`
	Replicas           *int32                    `json:"replicas,omitempty"`
	ReadyReplicas      *int32                    `json:"readyReplicas,omitempty"`
	CurrentReplicas    *int32                    `json:"currentReplicas,omitempty"`
	UpdatedReplicas    *int32                    `json:"updatedReplicas,omitempty"`
	CurrentRevision    *string                   `json:"currentRevision,omitempty"`
	UpdateRevision     *string                   `json:"updateRevision,omitempty"`
	CollisionCount     *int32                    `json:"collisionCount,omitempty"`
	Conditions         *StatefulSetConditionList `json:"conditions,omitempty"`
}

// SetObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value.
func (b *StatefulSetStatusApplyConfiguration) SetObservedGeneration(value int64) *StatefulSetStatusApplyConfiguration {
	b.fields.ObservedGeneration = &value
	return b
}

// RemoveObservedGeneration removes the ObservedGeneration field from the declarative configuration.
func (b *StatefulSetStatusApplyConfiguration) RemoveObservedGeneration() *StatefulSetStatusApplyConfiguration {
	b.fields.ObservedGeneration = nil
	return b
}

// GetObservedGeneration gets the ObservedGeneration field from the declarative configuration.
func (b *StatefulSetStatusApplyConfiguration) GetObservedGeneration() (value int64, ok bool) {
	if v := b.fields.ObservedGeneration; v != nil {
		return *v, true
	}
	return value, false
}

// SetReplicas sets the Replicas field in the declarative configuration to the given value.
func (b *StatefulSetStatusApplyConfiguration) SetReplicas(value int32) *StatefulSetStatusApplyConfiguration {
	b.fields.Replicas = &value
	return b
}

// RemoveReplicas removes the Replicas field from the declarative configuration.
func (b *StatefulSetStatusApplyConfiguration) RemoveReplicas() *StatefulSetStatusApplyConfiguration {
	b.fields.Replicas = nil
	return b
}

// GetReplicas gets the Replicas field from the declarative configuration.
func (b *StatefulSetStatusApplyConfiguration) GetReplicas() (value int32, ok bool) {
	if v := b.fields.Replicas; v != nil {
		return *v, true
	}
	return value, false
}

// SetReadyReplicas sets the ReadyReplicas field in the declarative configuration to the given value.
func (b *StatefulSetStatusApplyConfiguration) SetReadyReplicas(value int32) *StatefulSetStatusApplyConfiguration {
	b.fields.ReadyReplicas = &value
	return b
}

// RemoveReadyReplicas removes the ReadyReplicas field from the declarative configuration.
func (b *StatefulSetStatusApplyConfiguration) RemoveReadyReplicas() *StatefulSetStatusApplyConfiguration {
	b.fields.ReadyReplicas = nil
	return b
}

// GetReadyReplicas gets the ReadyReplicas field from the declarative configuration.
func (b *StatefulSetStatusApplyConfiguration) GetReadyReplicas() (value int32, ok bool) {
	if v := b.fields.ReadyReplicas; v != nil {
		return *v, true
	}
	return value, false
}

// SetCurrentReplicas sets the CurrentReplicas field in the declarative configuration to the given value.
func (b *StatefulSetStatusApplyConfiguration) SetCurrentReplicas(value int32) *StatefulSetStatusApplyConfiguration {
	b.fields.CurrentReplicas = &value
	return b
}

// RemoveCurrentReplicas removes the CurrentReplicas field from the declarative configuration.
func (b *StatefulSetStatusApplyConfiguration) RemoveCurrentReplicas() *StatefulSetStatusApplyConfiguration {
	b.fields.CurrentReplicas = nil
	return b
}

// GetCurrentReplicas gets the CurrentReplicas field from the declarative configuration.
func (b *StatefulSetStatusApplyConfiguration) GetCurrentReplicas() (value int32, ok bool) {
	if v := b.fields.CurrentReplicas; v != nil {
		return *v, true
	}
	return value, false
}

// SetUpdatedReplicas sets the UpdatedReplicas field in the declarative configuration to the given value.
func (b *StatefulSetStatusApplyConfiguration) SetUpdatedReplicas(value int32) *StatefulSetStatusApplyConfiguration {
	b.fields.UpdatedReplicas = &value
	return b
}

// RemoveUpdatedReplicas removes the UpdatedReplicas field from the declarative configuration.
func (b *StatefulSetStatusApplyConfiguration) RemoveUpdatedReplicas() *StatefulSetStatusApplyConfiguration {
	b.fields.UpdatedReplicas = nil
	return b
}

// GetUpdatedReplicas gets the UpdatedReplicas field from the declarative configuration.
func (b *StatefulSetStatusApplyConfiguration) GetUpdatedReplicas() (value int32, ok bool) {
	if v := b.fields.UpdatedReplicas; v != nil {
		return *v, true
	}
	return value, false
}

// SetCurrentRevision sets the CurrentRevision field in the declarative configuration to the given value.
func (b *StatefulSetStatusApplyConfiguration) SetCurrentRevision(value string) *StatefulSetStatusApplyConfiguration {
	b.fields.CurrentRevision = &value
	return b
}

// RemoveCurrentRevision removes the CurrentRevision field from the declarative configuration.
func (b *StatefulSetStatusApplyConfiguration) RemoveCurrentRevision() *StatefulSetStatusApplyConfiguration {
	b.fields.CurrentRevision = nil
	return b
}

// GetCurrentRevision gets the CurrentRevision field from the declarative configuration.
func (b *StatefulSetStatusApplyConfiguration) GetCurrentRevision() (value string, ok bool) {
	if v := b.fields.CurrentRevision; v != nil {
		return *v, true
	}
	return value, false
}

// SetUpdateRevision sets the UpdateRevision field in the declarative configuration to the given value.
func (b *StatefulSetStatusApplyConfiguration) SetUpdateRevision(value string) *StatefulSetStatusApplyConfiguration {
	b.fields.UpdateRevision = &value
	return b
}

// RemoveUpdateRevision removes the UpdateRevision field from the declarative configuration.
func (b *StatefulSetStatusApplyConfiguration) RemoveUpdateRevision() *StatefulSetStatusApplyConfiguration {
	b.fields.UpdateRevision = nil
	return b
}

// GetUpdateRevision gets the UpdateRevision field from the declarative configuration.
func (b *StatefulSetStatusApplyConfiguration) GetUpdateRevision() (value string, ok bool) {
	if v := b.fields.UpdateRevision; v != nil {
		return *v, true
	}
	return value, false
}

// SetCollisionCount sets the CollisionCount field in the declarative configuration to the given value.
func (b *StatefulSetStatusApplyConfiguration) SetCollisionCount(value int32) *StatefulSetStatusApplyConfiguration {
	b.fields.CollisionCount = &value
	return b
}

// RemoveCollisionCount removes the CollisionCount field from the declarative configuration.
func (b *StatefulSetStatusApplyConfiguration) RemoveCollisionCount() *StatefulSetStatusApplyConfiguration {
	b.fields.CollisionCount = nil
	return b
}

// GetCollisionCount gets the CollisionCount field from the declarative configuration.
func (b *StatefulSetStatusApplyConfiguration) GetCollisionCount() (value int32, ok bool) {
	if v := b.fields.CollisionCount; v != nil {
		return *v, true
	}
	return value, false
}

// SetConditions sets the Conditions field in the declarative configuration to the given value.
func (b *StatefulSetStatusApplyConfiguration) SetConditions(value StatefulSetConditionList) *StatefulSetStatusApplyConfiguration {
	b.fields.Conditions = &value
	return b
}

// RemoveConditions removes the Conditions field from the declarative configuration.
func (b *StatefulSetStatusApplyConfiguration) RemoveConditions() *StatefulSetStatusApplyConfiguration {
	b.fields.Conditions = nil
	return b
}

// GetConditions gets the Conditions field from the declarative configuration.
func (b *StatefulSetStatusApplyConfiguration) GetConditions() (value StatefulSetConditionList, ok bool) {
	if v := b.fields.Conditions; v != nil {
		return *v, true
	}
	return value, false
}

// ToUnstructured converts StatefulSetStatusApplyConfiguration to unstructured.
func (b *StatefulSetStatusApplyConfiguration) ToUnstructured() interface{} {
	if b == nil {
		return nil
	}
	b.preMarshal()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(&b.fields)
	if err != nil {
		panic(err)
	}
	return u
}

// FromUnstructured converts unstructured to StatefulSetStatusApplyConfiguration, replacing the contents
// of StatefulSetStatusApplyConfiguration.
func (b *StatefulSetStatusApplyConfiguration) FromUnstructured(u map[string]interface{}) error {
	m := &statefulSetStatusFields{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u, m)
	if err != nil {
		return err
	}
	b.fields = *m
	b.postUnmarshal()
	return nil
}

// MarshalJSON marshals StatefulSetStatusApplyConfiguration to JSON.
func (b *StatefulSetStatusApplyConfiguration) MarshalJSON() ([]byte, error) {
	b.preMarshal()
	return json.Marshal(b.fields)
}

// UnmarshalJSON unmarshals JSON into StatefulSetStatusApplyConfiguration, replacing the contents of
// StatefulSetStatusApplyConfiguration.
func (b *StatefulSetStatusApplyConfiguration) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &b.fields); err != nil {
		return err
	}
	b.postUnmarshal()
	return nil
}

// StatefulSetStatusList represents a listAlias of StatefulSetStatusApplyConfiguration.
type StatefulSetStatusList []*StatefulSetStatusApplyConfiguration

// StatefulSetStatusList represents a map of StatefulSetStatusApplyConfiguration.
type StatefulSetStatusMap map[string]StatefulSetStatusApplyConfiguration

func (b *StatefulSetStatusApplyConfiguration) preMarshal() {
}
func (b *StatefulSetStatusApplyConfiguration) postUnmarshal() {
}
