/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// CephFSPersistentVolumeSourceApplyConfiguration represents an declarative configuration of the CephFSPersistentVolumeSource type for use
// with apply.
type CephFSPersistentVolumeSourceApplyConfiguration struct {
	Monitors   *[]string                          `json:"monitors,omitempty"`
	Path       *string                            `json:"path,omitempty"`
	User       *string                            `json:"user,omitempty"`
	SecretFile *string                            `json:"secretFile,omitempty"`
	SecretRef  *SecretReferenceApplyConfiguration `json:"secretRef,omitempty"`
	ReadOnly   *bool                              `json:"readOnly,omitempty"`
}

// CephFSPersistentVolumeSourceApplyConfiguration constructs an declarative configuration of the CephFSPersistentVolumeSource type for use with
// apply.
func CephFSPersistentVolumeSource() *CephFSPersistentVolumeSourceApplyConfiguration {
	return &CephFSPersistentVolumeSourceApplyConfiguration{}
}

// SetMonitors sets the Monitors field in the declarative configuration to the given value.
func (b *CephFSPersistentVolumeSourceApplyConfiguration) SetMonitors(value []string) *CephFSPersistentVolumeSourceApplyConfiguration {
	b.Monitors = &value
	return b
}

// SetPath sets the Path field in the declarative configuration to the given value.
func (b *CephFSPersistentVolumeSourceApplyConfiguration) SetPath(value string) *CephFSPersistentVolumeSourceApplyConfiguration {
	b.Path = &value
	return b
}

// SetUser sets the User field in the declarative configuration to the given value.
func (b *CephFSPersistentVolumeSourceApplyConfiguration) SetUser(value string) *CephFSPersistentVolumeSourceApplyConfiguration {
	b.User = &value
	return b
}

// SetSecretFile sets the SecretFile field in the declarative configuration to the given value.
func (b *CephFSPersistentVolumeSourceApplyConfiguration) SetSecretFile(value string) *CephFSPersistentVolumeSourceApplyConfiguration {
	b.SecretFile = &value
	return b
}

// SetSecretRef sets the SecretRef field in the declarative configuration to the given value.
func (b *CephFSPersistentVolumeSourceApplyConfiguration) SetSecretRef(value *SecretReferenceApplyConfiguration) *CephFSPersistentVolumeSourceApplyConfiguration {
	b.SecretRef = value
	return b
}

// SetReadOnly sets the ReadOnly field in the declarative configuration to the given value.
func (b *CephFSPersistentVolumeSourceApplyConfiguration) SetReadOnly(value bool) *CephFSPersistentVolumeSourceApplyConfiguration {
	b.ReadOnly = &value
	return b
}
