/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	json "encoding/json"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

// CinderPersistentVolumeSourceApplyConfiguration represents an declarative configuration of the CinderPersistentVolumeSource type for use
// with apply.
type CinderPersistentVolumeSourceApplyConfiguration struct {
	fields cinderPersistentVolumeSourceFields
}

// CinderPersistentVolumeSourceApplyConfiguration constructs an declarative configuration of the CinderPersistentVolumeSource type for use with
// apply.
func CinderPersistentVolumeSource() *CinderPersistentVolumeSourceApplyConfiguration {
	return &CinderPersistentVolumeSourceApplyConfiguration{}
}

// cinderPersistentVolumeSourceFields owns all fields except inlined fields.
// Inline fields are owned by their respective inline type in CinderPersistentVolumeSourceApplyConfiguration.
// They are copied to this type before marshalling, and are copied out
// after unmarshalling. The inlined types cannot be embedded because they do
// not expose their fields directly.
type cinderPersistentVolumeSourceFields struct {
	VolumeID  *string                            `json:"volumeID,omitempty"`
	FSType    *string                            `json:"fsType,omitempty"`
	ReadOnly  *bool                              `json:"readOnly,omitempty"`
	SecretRef *SecretReferenceApplyConfiguration `json:"secretRef,omitempty"`
}

// SetVolumeID sets the VolumeID field in the declarative configuration to the given value.
func (b *CinderPersistentVolumeSourceApplyConfiguration) SetVolumeID(value string) *CinderPersistentVolumeSourceApplyConfiguration {
	b.fields.VolumeID = &value
	return b
}

// RemoveVolumeID removes the VolumeID field from the declarative configuration.
func (b *CinderPersistentVolumeSourceApplyConfiguration) RemoveVolumeID() *CinderPersistentVolumeSourceApplyConfiguration {
	b.fields.VolumeID = nil
	return b
}

// GetVolumeID gets the VolumeID field from the declarative configuration.
func (b *CinderPersistentVolumeSourceApplyConfiguration) GetVolumeID() (value string, ok bool) {
	if v := b.fields.VolumeID; v != nil {
		return *v, true
	}
	return value, false
}

// SetFSType sets the FSType field in the declarative configuration to the given value.
func (b *CinderPersistentVolumeSourceApplyConfiguration) SetFSType(value string) *CinderPersistentVolumeSourceApplyConfiguration {
	b.fields.FSType = &value
	return b
}

// RemoveFSType removes the FSType field from the declarative configuration.
func (b *CinderPersistentVolumeSourceApplyConfiguration) RemoveFSType() *CinderPersistentVolumeSourceApplyConfiguration {
	b.fields.FSType = nil
	return b
}

// GetFSType gets the FSType field from the declarative configuration.
func (b *CinderPersistentVolumeSourceApplyConfiguration) GetFSType() (value string, ok bool) {
	if v := b.fields.FSType; v != nil {
		return *v, true
	}
	return value, false
}

// SetReadOnly sets the ReadOnly field in the declarative configuration to the given value.
func (b *CinderPersistentVolumeSourceApplyConfiguration) SetReadOnly(value bool) *CinderPersistentVolumeSourceApplyConfiguration {
	b.fields.ReadOnly = &value
	return b
}

// RemoveReadOnly removes the ReadOnly field from the declarative configuration.
func (b *CinderPersistentVolumeSourceApplyConfiguration) RemoveReadOnly() *CinderPersistentVolumeSourceApplyConfiguration {
	b.fields.ReadOnly = nil
	return b
}

// GetReadOnly gets the ReadOnly field from the declarative configuration.
func (b *CinderPersistentVolumeSourceApplyConfiguration) GetReadOnly() (value bool, ok bool) {
	if v := b.fields.ReadOnly; v != nil {
		return *v, true
	}
	return value, false
}

// SetSecretRef sets the SecretRef field in the declarative configuration to the given value.
func (b *CinderPersistentVolumeSourceApplyConfiguration) SetSecretRef(value *SecretReferenceApplyConfiguration) *CinderPersistentVolumeSourceApplyConfiguration {
	b.fields.SecretRef = value
	return b
}

// RemoveSecretRef removes the SecretRef field from the declarative configuration.
func (b *CinderPersistentVolumeSourceApplyConfiguration) RemoveSecretRef() *CinderPersistentVolumeSourceApplyConfiguration {
	b.fields.SecretRef = nil
	return b
}

// GetSecretRef gets the SecretRef field from the declarative configuration.
func (b *CinderPersistentVolumeSourceApplyConfiguration) GetSecretRef() (value *SecretReferenceApplyConfiguration, ok bool) {
	return b.fields.SecretRef, b.fields.SecretRef != nil
}

// ToUnstructured converts CinderPersistentVolumeSourceApplyConfiguration to unstructured.
func (b *CinderPersistentVolumeSourceApplyConfiguration) ToUnstructured() interface{} {
	if b == nil {
		return nil
	}
	b.preMarshal()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(&b.fields)
	if err != nil {
		panic(err)
	}
	return u
}

// FromUnstructured converts unstructured to CinderPersistentVolumeSourceApplyConfiguration, replacing the contents
// of CinderPersistentVolumeSourceApplyConfiguration.
func (b *CinderPersistentVolumeSourceApplyConfiguration) FromUnstructured(u map[string]interface{}) error {
	m := &cinderPersistentVolumeSourceFields{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u, m)
	if err != nil {
		return err
	}
	b.fields = *m
	b.postUnmarshal()
	return nil
}

// MarshalJSON marshals CinderPersistentVolumeSourceApplyConfiguration to JSON.
func (b *CinderPersistentVolumeSourceApplyConfiguration) MarshalJSON() ([]byte, error) {
	b.preMarshal()
	return json.Marshal(b.fields)
}

// UnmarshalJSON unmarshals JSON into CinderPersistentVolumeSourceApplyConfiguration, replacing the contents of
// CinderPersistentVolumeSourceApplyConfiguration.
func (b *CinderPersistentVolumeSourceApplyConfiguration) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &b.fields); err != nil {
		return err
	}
	b.postUnmarshal()
	return nil
}

// CinderPersistentVolumeSourceList represents a listAlias of CinderPersistentVolumeSourceApplyConfiguration.
type CinderPersistentVolumeSourceList []*CinderPersistentVolumeSourceApplyConfiguration

// CinderPersistentVolumeSourceList represents a map of CinderPersistentVolumeSourceApplyConfiguration.
type CinderPersistentVolumeSourceMap map[string]CinderPersistentVolumeSourceApplyConfiguration

func (b *CinderPersistentVolumeSourceApplyConfiguration) preMarshal() {
}
func (b *CinderPersistentVolumeSourceApplyConfiguration) postUnmarshal() {
}
