/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1 "k8s.io/api/core/v1"
)

// ContainerPortApplyConfiguration represents an declarative configuration of the ContainerPort type for use
// with apply.
type ContainerPortApplyConfiguration struct {
	Name          *string      `json:"name,omitempty"`
	HostPort      *int32       `json:"hostPort,omitempty"`
	ContainerPort *int32       `json:"containerPort,omitempty"`
	Protocol      *v1.Protocol `json:"protocol,omitempty"`
	HostIP        *string      `json:"hostIP,omitempty"`
}

// ContainerPortApplyConfiguration constructs an declarative configuration of the ContainerPort type for use with
// apply.
func ContainerPort() *ContainerPortApplyConfiguration {
	return &ContainerPortApplyConfiguration{}
}

// SetName sets the Name field in the declarative configuration to the given value.
func (b *ContainerPortApplyConfiguration) SetName(value string) *ContainerPortApplyConfiguration {
	b.Name = &value
	return b
}

// SetHostPort sets the HostPort field in the declarative configuration to the given value.
func (b *ContainerPortApplyConfiguration) SetHostPort(value int32) *ContainerPortApplyConfiguration {
	b.HostPort = &value
	return b
}

// SetContainerPort sets the ContainerPort field in the declarative configuration to the given value.
func (b *ContainerPortApplyConfiguration) SetContainerPort(value int32) *ContainerPortApplyConfiguration {
	b.ContainerPort = &value
	return b
}

// SetProtocol sets the Protocol field in the declarative configuration to the given value.
func (b *ContainerPortApplyConfiguration) SetProtocol(value v1.Protocol) *ContainerPortApplyConfiguration {
	b.Protocol = &value
	return b
}

// SetHostIP sets the HostIP field in the declarative configuration to the given value.
func (b *ContainerPortApplyConfiguration) SetHostIP(value string) *ContainerPortApplyConfiguration {
	b.HostIP = &value
	return b
}
