/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	json "encoding/json"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

// GlusterfsPersistentVolumeSourceApplyConfiguration represents an declarative configuration of the GlusterfsPersistentVolumeSource type for use
// with apply.
type GlusterfsPersistentVolumeSourceApplyConfiguration struct {
	fields glusterfsPersistentVolumeSourceFields
}

// GlusterfsPersistentVolumeSourceApplyConfiguration constructs an declarative configuration of the GlusterfsPersistentVolumeSource type for use with
// apply.
func GlusterfsPersistentVolumeSource() *GlusterfsPersistentVolumeSourceApplyConfiguration {
	return &GlusterfsPersistentVolumeSourceApplyConfiguration{}
}

// glusterfsPersistentVolumeSourceFields owns all fields except inlined fields.
// Inline fields are owned by their respective inline type in GlusterfsPersistentVolumeSourceApplyConfiguration.
// They are copied to this type before marshalling, and are copied out
// after unmarshalling. The inlined types cannot be embedded because they do
// not expose their fields directly.
type glusterfsPersistentVolumeSourceFields struct {
	EndpointsName      *string `json:"endpoints,omitempty"`
	Path               *string `json:"path,omitempty"`
	ReadOnly           *bool   `json:"readOnly,omitempty"`
	EndpointsNamespace *string `json:"endpointsNamespace,omitempty"`
}

// SetEndpointsName sets the EndpointsName field in the declarative configuration to the given value.
func (b *GlusterfsPersistentVolumeSourceApplyConfiguration) SetEndpointsName(value string) *GlusterfsPersistentVolumeSourceApplyConfiguration {
	b.fields.EndpointsName = &value
	return b
}

// RemoveEndpointsName removes the EndpointsName field from the declarative configuration.
func (b *GlusterfsPersistentVolumeSourceApplyConfiguration) RemoveEndpointsName() *GlusterfsPersistentVolumeSourceApplyConfiguration {
	b.fields.EndpointsName = nil
	return b
}

// GetEndpointsName gets the EndpointsName field from the declarative configuration.
func (b *GlusterfsPersistentVolumeSourceApplyConfiguration) GetEndpointsName() (value string, ok bool) {
	if v := b.fields.EndpointsName; v != nil {
		return *v, true
	}
	return value, false
}

// SetPath sets the Path field in the declarative configuration to the given value.
func (b *GlusterfsPersistentVolumeSourceApplyConfiguration) SetPath(value string) *GlusterfsPersistentVolumeSourceApplyConfiguration {
	b.fields.Path = &value
	return b
}

// RemovePath removes the Path field from the declarative configuration.
func (b *GlusterfsPersistentVolumeSourceApplyConfiguration) RemovePath() *GlusterfsPersistentVolumeSourceApplyConfiguration {
	b.fields.Path = nil
	return b
}

// GetPath gets the Path field from the declarative configuration.
func (b *GlusterfsPersistentVolumeSourceApplyConfiguration) GetPath() (value string, ok bool) {
	if v := b.fields.Path; v != nil {
		return *v, true
	}
	return value, false
}

// SetReadOnly sets the ReadOnly field in the declarative configuration to the given value.
func (b *GlusterfsPersistentVolumeSourceApplyConfiguration) SetReadOnly(value bool) *GlusterfsPersistentVolumeSourceApplyConfiguration {
	b.fields.ReadOnly = &value
	return b
}

// RemoveReadOnly removes the ReadOnly field from the declarative configuration.
func (b *GlusterfsPersistentVolumeSourceApplyConfiguration) RemoveReadOnly() *GlusterfsPersistentVolumeSourceApplyConfiguration {
	b.fields.ReadOnly = nil
	return b
}

// GetReadOnly gets the ReadOnly field from the declarative configuration.
func (b *GlusterfsPersistentVolumeSourceApplyConfiguration) GetReadOnly() (value bool, ok bool) {
	if v := b.fields.ReadOnly; v != nil {
		return *v, true
	}
	return value, false
}

// SetEndpointsNamespace sets the EndpointsNamespace field in the declarative configuration to the given value.
func (b *GlusterfsPersistentVolumeSourceApplyConfiguration) SetEndpointsNamespace(value string) *GlusterfsPersistentVolumeSourceApplyConfiguration {
	b.fields.EndpointsNamespace = &value
	return b
}

// RemoveEndpointsNamespace removes the EndpointsNamespace field from the declarative configuration.
func (b *GlusterfsPersistentVolumeSourceApplyConfiguration) RemoveEndpointsNamespace() *GlusterfsPersistentVolumeSourceApplyConfiguration {
	b.fields.EndpointsNamespace = nil
	return b
}

// GetEndpointsNamespace gets the EndpointsNamespace field from the declarative configuration.
func (b *GlusterfsPersistentVolumeSourceApplyConfiguration) GetEndpointsNamespace() (value string, ok bool) {
	if v := b.fields.EndpointsNamespace; v != nil {
		return *v, true
	}
	return value, false
}

// ToUnstructured converts GlusterfsPersistentVolumeSourceApplyConfiguration to unstructured.
func (b *GlusterfsPersistentVolumeSourceApplyConfiguration) ToUnstructured() interface{} {
	if b == nil {
		return nil
	}
	b.preMarshal()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(&b.fields)
	if err != nil {
		panic(err)
	}
	return u
}

// FromUnstructured converts unstructured to GlusterfsPersistentVolumeSourceApplyConfiguration, replacing the contents
// of GlusterfsPersistentVolumeSourceApplyConfiguration.
func (b *GlusterfsPersistentVolumeSourceApplyConfiguration) FromUnstructured(u map[string]interface{}) error {
	m := &glusterfsPersistentVolumeSourceFields{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u, m)
	if err != nil {
		return err
	}
	b.fields = *m
	b.postUnmarshal()
	return nil
}

// MarshalJSON marshals GlusterfsPersistentVolumeSourceApplyConfiguration to JSON.
func (b *GlusterfsPersistentVolumeSourceApplyConfiguration) MarshalJSON() ([]byte, error) {
	b.preMarshal()
	return json.Marshal(b.fields)
}

// UnmarshalJSON unmarshals JSON into GlusterfsPersistentVolumeSourceApplyConfiguration, replacing the contents of
// GlusterfsPersistentVolumeSourceApplyConfiguration.
func (b *GlusterfsPersistentVolumeSourceApplyConfiguration) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &b.fields); err != nil {
		return err
	}
	b.postUnmarshal()
	return nil
}

// GlusterfsPersistentVolumeSourceList represents a listAlias of GlusterfsPersistentVolumeSourceApplyConfiguration.
type GlusterfsPersistentVolumeSourceList []*GlusterfsPersistentVolumeSourceApplyConfiguration

// GlusterfsPersistentVolumeSourceList represents a map of GlusterfsPersistentVolumeSourceApplyConfiguration.
type GlusterfsPersistentVolumeSourceMap map[string]GlusterfsPersistentVolumeSourceApplyConfiguration

func (b *GlusterfsPersistentVolumeSourceApplyConfiguration) preMarshal() {
}
func (b *GlusterfsPersistentVolumeSourceApplyConfiguration) postUnmarshal() {
}
