/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by typebuilder-gen. DO NOT EDIT.

package v1alpha1

import (
	json "encoding/json"

	v1alpha1 "k8s.io/api/flowcontrol/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// FlowSchemaConditionBuilder represents an declarative configuration of the FlowSchemaCondition type for use
// with apply.
type FlowSchemaConditionBuilder struct {
	fields *flowSchemaConditionFields
}

// flowSchemaConditionFields is used by FlowSchemaConditionBuilder for json marshalling and unmarshalling.
// Is the source-of-truth for all fields except inlined fields.
// Inline fields are copied in from their builder type in FlowSchemaConditionBuilder before marshalling, and
// are copied out to the builder type in FlowSchemaConditionBuilder after unmarshalling.
// Inlined builder types cannot be embedded because they do not expose their fields directly.
type flowSchemaConditionFields struct {
	Type               *v1alpha1.FlowSchemaConditionType `json:"type,omitempty"`
	Status             *v1alpha1.ConditionStatus         `json:"status,omitempty"`
	LastTransitionTime *v1.Time                          `json:"lastTransitionTime,omitempty"`
	Reason             *string                           `json:"reason,omitempty"`
	Message            *string                           `json:"message,omitempty"`
}

func (b *FlowSchemaConditionBuilder) ensureInitialized() {
	if b.fields == nil {
		b.fields = &flowSchemaConditionFields{}
	}
}

// FlowSchemaCondition constructs an declarative configuration of the FlowSchemaCondition type for use with
// apply.
// Provided as a convenience.
func FlowSchemaCondition() FlowSchemaConditionBuilder {
	return FlowSchemaConditionBuilder{fields: &flowSchemaConditionFields{}}
}

// SetType sets the Type field in the declarative configuration to the given value.
func (b FlowSchemaConditionBuilder) SetType(value v1alpha1.FlowSchemaConditionType) FlowSchemaConditionBuilder {
	b.ensureInitialized()
	b.fields.Type = &value
	return b
}

// RemoveType removes the Type field from the declarative configuration.
func (b FlowSchemaConditionBuilder) RemoveType() FlowSchemaConditionBuilder {
	b.ensureInitialized()
	b.fields.Type = nil
	return b
}

// GetType gets the Type field from the declarative configuration.
func (b FlowSchemaConditionBuilder) GetType() (value v1alpha1.FlowSchemaConditionType, ok bool) {
	b.ensureInitialized()
	if v := b.fields.Type; v != nil {
		return *v, true
	}
	return value, false
}

// SetStatus sets the Status field in the declarative configuration to the given value.
func (b FlowSchemaConditionBuilder) SetStatus(value v1alpha1.ConditionStatus) FlowSchemaConditionBuilder {
	b.ensureInitialized()
	b.fields.Status = &value
	return b
}

// RemoveStatus removes the Status field from the declarative configuration.
func (b FlowSchemaConditionBuilder) RemoveStatus() FlowSchemaConditionBuilder {
	b.ensureInitialized()
	b.fields.Status = nil
	return b
}

// GetStatus gets the Status field from the declarative configuration.
func (b FlowSchemaConditionBuilder) GetStatus() (value v1alpha1.ConditionStatus, ok bool) {
	b.ensureInitialized()
	if v := b.fields.Status; v != nil {
		return *v, true
	}
	return value, false
}

// SetLastTransitionTime sets the LastTransitionTime field in the declarative configuration to the given value.
func (b FlowSchemaConditionBuilder) SetLastTransitionTime(value v1.Time) FlowSchemaConditionBuilder {
	b.ensureInitialized()
	b.fields.LastTransitionTime = &value
	return b
}

// RemoveLastTransitionTime removes the LastTransitionTime field from the declarative configuration.
func (b FlowSchemaConditionBuilder) RemoveLastTransitionTime() FlowSchemaConditionBuilder {
	b.ensureInitialized()
	b.fields.LastTransitionTime = nil
	return b
}

// GetLastTransitionTime gets the LastTransitionTime field from the declarative configuration.
func (b FlowSchemaConditionBuilder) GetLastTransitionTime() (value v1.Time, ok bool) {
	b.ensureInitialized()
	if v := b.fields.LastTransitionTime; v != nil {
		return *v, true
	}
	return value, false
}

// SetReason sets the Reason field in the declarative configuration to the given value.
func (b FlowSchemaConditionBuilder) SetReason(value string) FlowSchemaConditionBuilder {
	b.ensureInitialized()
	b.fields.Reason = &value
	return b
}

// RemoveReason removes the Reason field from the declarative configuration.
func (b FlowSchemaConditionBuilder) RemoveReason() FlowSchemaConditionBuilder {
	b.ensureInitialized()
	b.fields.Reason = nil
	return b
}

// GetReason gets the Reason field from the declarative configuration.
func (b FlowSchemaConditionBuilder) GetReason() (value string, ok bool) {
	b.ensureInitialized()
	if v := b.fields.Reason; v != nil {
		return *v, true
	}
	return value, false
}

// SetMessage sets the Message field in the declarative configuration to the given value.
func (b FlowSchemaConditionBuilder) SetMessage(value string) FlowSchemaConditionBuilder {
	b.ensureInitialized()
	b.fields.Message = &value
	return b
}

// RemoveMessage removes the Message field from the declarative configuration.
func (b FlowSchemaConditionBuilder) RemoveMessage() FlowSchemaConditionBuilder {
	b.ensureInitialized()
	b.fields.Message = nil
	return b
}

// GetMessage gets the Message field from the declarative configuration.
func (b FlowSchemaConditionBuilder) GetMessage() (value string, ok bool) {
	b.ensureInitialized()
	if v := b.fields.Message; v != nil {
		return *v, true
	}
	return value, false
}

// ToUnstructured converts FlowSchemaConditionBuilder to unstructured.
func (b *FlowSchemaConditionBuilder) ToUnstructured() interface{} {
	if b == nil {
		return nil
	}
	b.ensureInitialized()
	b.preMarshal()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(b.fields)
	if err != nil {
		panic(err)
	}
	return u
}

// FromUnstructured converts unstructured to FlowSchemaConditionBuilder, replacing the contents
// of FlowSchemaConditionBuilder.
func (b *FlowSchemaConditionBuilder) FromUnstructured(u map[string]interface{}) error {
	m := &flowSchemaConditionFields{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u, m)
	if err != nil {
		return err
	}
	b.fields = m
	b.postUnmarshal()
	return nil
}

// MarshalJSON marshals FlowSchemaConditionBuilder to JSON.
func (b *FlowSchemaConditionBuilder) MarshalJSON() ([]byte, error) {
	u := &unstructured.Unstructured{Object: b.ToUnstructured().(map[string]interface{})}
	return u.MarshalJSON()
}

// UnmarshalJSON unmarshals JSON into FlowSchemaConditionBuilder, replacing the contents of
// FlowSchemaConditionBuilder.
func (b *FlowSchemaConditionBuilder) UnmarshalJSON(data []byte) error {
	b.ensureInitialized()
	if err := json.Unmarshal(data, b.fields); err != nil {
		return err
	}
	b.postUnmarshal()
	return nil
}

// FlowSchemaConditionList represents a list of FlowSchemaConditionBuilder.
// Provided as a convenience.
type FlowSchemaConditionList []FlowSchemaConditionBuilder

// FlowSchemaConditionList represents a map of FlowSchemaConditionBuilder.
// Provided as a convenience.
type FlowSchemaConditionMap map[string]FlowSchemaConditionBuilder

func (b *FlowSchemaConditionBuilder) preMarshal() {
}
func (b *FlowSchemaConditionBuilder) postUnmarshal() {
}
