/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by typebuilder-gen. DO NOT EDIT.

package v2beta1

import (
	json "encoding/json"

	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// HorizontalPodAutoscalerSpecBuilder represents an declarative configuration of the HorizontalPodAutoscalerSpec type for use
// with apply.
type HorizontalPodAutoscalerSpecBuilder struct {
	fields *horizontalPodAutoscalerSpecFields
}

// horizontalPodAutoscalerSpecFields is used by HorizontalPodAutoscalerSpecBuilder for json marshalling and unmarshalling.
// Is the source-of-truth for all fields except inlined fields.
// Inline fields are copied in from their builder type in HorizontalPodAutoscalerSpecBuilder before marshalling, and
// are copied out to the builder type in HorizontalPodAutoscalerSpecBuilder after unmarshalling.
// Inlined builder types cannot be embedded because they do not expose their fields directly.
type horizontalPodAutoscalerSpecFields struct {
	ScaleTargetRef *CrossVersionObjectReferenceBuilder `json:"scaleTargetRef,omitempty"`
	MinReplicas    *int32                              `json:"minReplicas,omitempty"`
	MaxReplicas    *int32                              `json:"maxReplicas,omitempty"`
	Metrics        *MetricSpecList                     `json:"metrics,omitempty"`
}

func (b *HorizontalPodAutoscalerSpecBuilder) ensureInitialized() {
	if b.fields == nil {
		b.fields = &horizontalPodAutoscalerSpecFields{}
	}
}

// HorizontalPodAutoscalerSpec constructs an declarative configuration of the HorizontalPodAutoscalerSpec type for use with
// apply.
// Provided as a convenience.
func HorizontalPodAutoscalerSpec() HorizontalPodAutoscalerSpecBuilder {
	return HorizontalPodAutoscalerSpecBuilder{fields: &horizontalPodAutoscalerSpecFields{}}
}

// SetScaleTargetRef sets the ScaleTargetRef field in the declarative configuration to the given value.
func (b HorizontalPodAutoscalerSpecBuilder) SetScaleTargetRef(value CrossVersionObjectReferenceBuilder) HorizontalPodAutoscalerSpecBuilder {
	b.ensureInitialized()
	b.fields.ScaleTargetRef = &value
	return b
}

// RemoveScaleTargetRef removes the ScaleTargetRef field from the declarative configuration.
func (b HorizontalPodAutoscalerSpecBuilder) RemoveScaleTargetRef() HorizontalPodAutoscalerSpecBuilder {
	b.ensureInitialized()
	b.fields.ScaleTargetRef = nil
	return b
}

// GetScaleTargetRef gets the ScaleTargetRef field from the declarative configuration.
func (b HorizontalPodAutoscalerSpecBuilder) GetScaleTargetRef() (value CrossVersionObjectReferenceBuilder, ok bool) {
	b.ensureInitialized()
	if v := b.fields.ScaleTargetRef; v != nil {
		return *v, true
	}
	return value, false
}

// SetMinReplicas sets the MinReplicas field in the declarative configuration to the given value.
func (b HorizontalPodAutoscalerSpecBuilder) SetMinReplicas(value int32) HorizontalPodAutoscalerSpecBuilder {
	b.ensureInitialized()
	b.fields.MinReplicas = &value
	return b
}

// RemoveMinReplicas removes the MinReplicas field from the declarative configuration.
func (b HorizontalPodAutoscalerSpecBuilder) RemoveMinReplicas() HorizontalPodAutoscalerSpecBuilder {
	b.ensureInitialized()
	b.fields.MinReplicas = nil
	return b
}

// GetMinReplicas gets the MinReplicas field from the declarative configuration.
func (b HorizontalPodAutoscalerSpecBuilder) GetMinReplicas() (value int32, ok bool) {
	b.ensureInitialized()
	if v := b.fields.MinReplicas; v != nil {
		return *v, true
	}
	return value, false
}

// SetMaxReplicas sets the MaxReplicas field in the declarative configuration to the given value.
func (b HorizontalPodAutoscalerSpecBuilder) SetMaxReplicas(value int32) HorizontalPodAutoscalerSpecBuilder {
	b.ensureInitialized()
	b.fields.MaxReplicas = &value
	return b
}

// RemoveMaxReplicas removes the MaxReplicas field from the declarative configuration.
func (b HorizontalPodAutoscalerSpecBuilder) RemoveMaxReplicas() HorizontalPodAutoscalerSpecBuilder {
	b.ensureInitialized()
	b.fields.MaxReplicas = nil
	return b
}

// GetMaxReplicas gets the MaxReplicas field from the declarative configuration.
func (b HorizontalPodAutoscalerSpecBuilder) GetMaxReplicas() (value int32, ok bool) {
	b.ensureInitialized()
	if v := b.fields.MaxReplicas; v != nil {
		return *v, true
	}
	return value, false
}

// SetMetrics sets the Metrics field in the declarative configuration to the given value.
func (b HorizontalPodAutoscalerSpecBuilder) SetMetrics(value MetricSpecList) HorizontalPodAutoscalerSpecBuilder {
	b.ensureInitialized()
	b.fields.Metrics = &value
	return b
}

// RemoveMetrics removes the Metrics field from the declarative configuration.
func (b HorizontalPodAutoscalerSpecBuilder) RemoveMetrics() HorizontalPodAutoscalerSpecBuilder {
	b.ensureInitialized()
	b.fields.Metrics = nil
	return b
}

// GetMetrics gets the Metrics field from the declarative configuration.
func (b HorizontalPodAutoscalerSpecBuilder) GetMetrics() (value MetricSpecList, ok bool) {
	b.ensureInitialized()
	if v := b.fields.Metrics; v != nil {
		return *v, true
	}
	return value, false
}

// ToUnstructured converts HorizontalPodAutoscalerSpecBuilder to unstructured.
func (b *HorizontalPodAutoscalerSpecBuilder) ToUnstructured() interface{} {
	if b == nil {
		return nil
	}
	b.ensureInitialized()
	b.preMarshal()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(b.fields)
	if err != nil {
		panic(err)
	}
	return u
}

// FromUnstructured converts unstructured to HorizontalPodAutoscalerSpecBuilder, replacing the contents
// of HorizontalPodAutoscalerSpecBuilder.
func (b *HorizontalPodAutoscalerSpecBuilder) FromUnstructured(u map[string]interface{}) error {
	m := &horizontalPodAutoscalerSpecFields{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u, m)
	if err != nil {
		return err
	}
	b.fields = m
	b.postUnmarshal()
	return nil
}

// MarshalJSON marshals HorizontalPodAutoscalerSpecBuilder to JSON.
func (b *HorizontalPodAutoscalerSpecBuilder) MarshalJSON() ([]byte, error) {
	u := &unstructured.Unstructured{Object: b.ToUnstructured().(map[string]interface{})}
	return u.MarshalJSON()
}

// UnmarshalJSON unmarshals JSON into HorizontalPodAutoscalerSpecBuilder, replacing the contents of
// HorizontalPodAutoscalerSpecBuilder.
func (b *HorizontalPodAutoscalerSpecBuilder) UnmarshalJSON(data []byte) error {
	b.ensureInitialized()
	if err := json.Unmarshal(data, b.fields); err != nil {
		return err
	}
	b.postUnmarshal()
	return nil
}

// HorizontalPodAutoscalerSpecList represents a list of HorizontalPodAutoscalerSpecBuilder.
// Provided as a convenience.
type HorizontalPodAutoscalerSpecList []HorizontalPodAutoscalerSpecBuilder

// HorizontalPodAutoscalerSpecList represents a map of HorizontalPodAutoscalerSpecBuilder.
// Provided as a convenience.
type HorizontalPodAutoscalerSpecMap map[string]HorizontalPodAutoscalerSpecBuilder

func (b *HorizontalPodAutoscalerSpecBuilder) preMarshal() {
}
func (b *HorizontalPodAutoscalerSpecBuilder) postUnmarshal() {
}
