/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by typebuilder-gen. DO NOT EDIT.

package v1

import (
	json "encoding/json"

	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// CSINodeDriverBuilder represents an declarative configuration of the CSINodeDriver type for use
// with apply.
type CSINodeDriverBuilder struct {
	fields *cSINodeDriverFields
}

// cSINodeDriverFields is used by CSINodeDriverBuilder for json marshalling and unmarshalling.
// Is the source-of-truth for all fields except inlined fields.
// Inline fields are copied in from their builder type in CSINodeDriverBuilder before marshalling, and
// are copied out to the builder type in CSINodeDriverBuilder after unmarshalling.
// Inlined builder types cannot be embedded because they do not expose their fields directly.
type cSINodeDriverFields struct {
	Name         *string                     `json:"name,omitempty"`
	NodeID       *string                     `json:"nodeID,omitempty"`
	TopologyKeys *[]string                   `json:"topologyKeys,omitempty"`
	Allocatable  *VolumeNodeResourcesBuilder `json:"allocatable,omitempty"`
}

func (b *CSINodeDriverBuilder) ensureInitialized() {
	if b.fields == nil {
		b.fields = &cSINodeDriverFields{}
	}
}

// CSINodeDriver constructs an declarative configuration of the CSINodeDriver type for use with
// apply.
// Provided as a convenience.
func CSINodeDriver() CSINodeDriverBuilder {
	return CSINodeDriverBuilder{fields: &cSINodeDriverFields{}}
}

// SetName sets the Name field in the declarative configuration to the given value.
func (b CSINodeDriverBuilder) SetName(value string) CSINodeDriverBuilder {
	b.ensureInitialized()
	b.fields.Name = &value
	return b
}

// RemoveName removes the Name field from the declarative configuration.
func (b CSINodeDriverBuilder) RemoveName() CSINodeDriverBuilder {
	b.ensureInitialized()
	b.fields.Name = nil
	return b
}

// GetName gets the Name field from the declarative configuration.
func (b CSINodeDriverBuilder) GetName() (value string, ok bool) {
	b.ensureInitialized()
	if v := b.fields.Name; v != nil {
		return *v, true
	}
	return value, false
}

// SetNodeID sets the NodeID field in the declarative configuration to the given value.
func (b CSINodeDriverBuilder) SetNodeID(value string) CSINodeDriverBuilder {
	b.ensureInitialized()
	b.fields.NodeID = &value
	return b
}

// RemoveNodeID removes the NodeID field from the declarative configuration.
func (b CSINodeDriverBuilder) RemoveNodeID() CSINodeDriverBuilder {
	b.ensureInitialized()
	b.fields.NodeID = nil
	return b
}

// GetNodeID gets the NodeID field from the declarative configuration.
func (b CSINodeDriverBuilder) GetNodeID() (value string, ok bool) {
	b.ensureInitialized()
	if v := b.fields.NodeID; v != nil {
		return *v, true
	}
	return value, false
}

// SetTopologyKeys sets the TopologyKeys field in the declarative configuration to the given value.
func (b CSINodeDriverBuilder) SetTopologyKeys(value []string) CSINodeDriverBuilder {
	b.ensureInitialized()
	b.fields.TopologyKeys = &value
	return b
}

// RemoveTopologyKeys removes the TopologyKeys field from the declarative configuration.
func (b CSINodeDriverBuilder) RemoveTopologyKeys() CSINodeDriverBuilder {
	b.ensureInitialized()
	b.fields.TopologyKeys = nil
	return b
}

// GetTopologyKeys gets the TopologyKeys field from the declarative configuration.
func (b CSINodeDriverBuilder) GetTopologyKeys() (value []string, ok bool) {
	b.ensureInitialized()
	if v := b.fields.TopologyKeys; v != nil {
		return *v, true
	}
	return value, false
}

// SetAllocatable sets the Allocatable field in the declarative configuration to the given value.
func (b CSINodeDriverBuilder) SetAllocatable(value VolumeNodeResourcesBuilder) CSINodeDriverBuilder {
	b.ensureInitialized()
	b.fields.Allocatable = &value
	return b
}

// RemoveAllocatable removes the Allocatable field from the declarative configuration.
func (b CSINodeDriverBuilder) RemoveAllocatable() CSINodeDriverBuilder {
	b.ensureInitialized()
	b.fields.Allocatable = nil
	return b
}

// GetAllocatable gets the Allocatable field from the declarative configuration.
func (b CSINodeDriverBuilder) GetAllocatable() (value VolumeNodeResourcesBuilder, ok bool) {
	b.ensureInitialized()
	if v := b.fields.Allocatable; v != nil {
		return *v, true
	}
	return value, false
}

// ToUnstructured converts CSINodeDriverBuilder to unstructured.
func (b *CSINodeDriverBuilder) ToUnstructured() interface{} {
	if b == nil {
		return nil
	}
	b.ensureInitialized()
	b.preMarshal()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(b.fields)
	if err != nil {
		panic(err)
	}
	return u
}

// FromUnstructured converts unstructured to CSINodeDriverBuilder, replacing the contents
// of CSINodeDriverBuilder.
func (b *CSINodeDriverBuilder) FromUnstructured(u map[string]interface{}) error {
	m := &cSINodeDriverFields{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u, m)
	if err != nil {
		return err
	}
	b.fields = m
	b.postUnmarshal()
	return nil
}

// MarshalJSON marshals CSINodeDriverBuilder to JSON.
func (b *CSINodeDriverBuilder) MarshalJSON() ([]byte, error) {
	u := &unstructured.Unstructured{Object: b.ToUnstructured().(map[string]interface{})}
	return u.MarshalJSON()
}

// UnmarshalJSON unmarshals JSON into CSINodeDriverBuilder, replacing the contents of
// CSINodeDriverBuilder.
func (b *CSINodeDriverBuilder) UnmarshalJSON(data []byte) error {
	b.ensureInitialized()
	if err := json.Unmarshal(data, b.fields); err != nil {
		return err
	}
	b.postUnmarshal()
	return nil
}

// CSINodeDriverList represents a list of CSINodeDriverBuilder.
// Provided as a convenience.
type CSINodeDriverList []CSINodeDriverBuilder

// CSINodeDriverList represents a map of CSINodeDriverBuilder.
// Provided as a convenience.
type CSINodeDriverMap map[string]CSINodeDriverBuilder

func (b *CSINodeDriverBuilder) preMarshal() {
}
func (b *CSINodeDriverBuilder) postUnmarshal() {
}
