/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// ExtensionMetaApplyConfiguration represents an declarative configuration of the ExtensionMeta type for use
// with apply.
type ExtensionMetaApplyConfiguration struct {
	Extensions map[string]runtime.RawExtension `json:"extensions,omitempty"`
}

// ExtensionMetaApplyConfiguration constructs an declarative configuration of the ExtensionMeta type for use with
// apply.
func ExtensionMeta() *ExtensionMetaApplyConfiguration {
	return &ExtensionMetaApplyConfiguration{}
}

// WithExtensions puts the entries into the Extensions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Extensions field,
// overwriting an existing map entries in Extensions field with the same key.
func (b *ExtensionMetaApplyConfiguration) WithExtensions(entries map[string]runtime.RawExtension) *ExtensionMetaApplyConfiguration {
	if b.Extensions == nil && len(entries) > 0 {
		b.Extensions = make(map[string]runtime.RawExtension, len(entries))
	}
	for k, v := range entries {
		b.Extensions[k] = v
	}
	return b
}
