/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	json "encoding/json"

	runtime "k8s.io/apimachinery/pkg/runtime"
	types "k8s.io/apimachinery/pkg/types"
)

// PreconditionsApplyConfiguration represents an declarative configuration of the Preconditions type for use
// with apply.
type PreconditionsApplyConfiguration struct {
	fields preconditionsFields
}

// PreconditionsApplyConfiguration constructs an declarative configuration of the Preconditions type for use with
// apply.
func Preconditions() *PreconditionsApplyConfiguration {
	return &PreconditionsApplyConfiguration{}
}

// preconditionsFields owns all fields except inlined fields.
// Inline fields are owned by their respective inline type in PreconditionsApplyConfiguration.
// They are copied to this type before marshalling, and are copied out
// after unmarshalling. The inlined types cannot be embedded because they do
// not expose their fields directly.
type preconditionsFields struct {
	UID             *types.UID `json:"uid,omitempty"`
	ResourceVersion *string    `json:"resourceVersion,omitempty"`
}

// SetUID sets the UID field in the declarative configuration to the given value.
func (b *PreconditionsApplyConfiguration) SetUID(value types.UID) *PreconditionsApplyConfiguration {
	b.fields.UID = &value
	return b
}

// RemoveUID removes the UID field from the declarative configuration.
func (b *PreconditionsApplyConfiguration) RemoveUID() *PreconditionsApplyConfiguration {
	b.fields.UID = nil
	return b
}

// GetUID gets the UID field from the declarative configuration.
func (b *PreconditionsApplyConfiguration) GetUID() (value types.UID, ok bool) {
	if v := b.fields.UID; v != nil {
		return *v, true
	}
	return value, false
}

// SetResourceVersion sets the ResourceVersion field in the declarative configuration to the given value.
func (b *PreconditionsApplyConfiguration) SetResourceVersion(value string) *PreconditionsApplyConfiguration {
	b.fields.ResourceVersion = &value
	return b
}

// RemoveResourceVersion removes the ResourceVersion field from the declarative configuration.
func (b *PreconditionsApplyConfiguration) RemoveResourceVersion() *PreconditionsApplyConfiguration {
	b.fields.ResourceVersion = nil
	return b
}

// GetResourceVersion gets the ResourceVersion field from the declarative configuration.
func (b *PreconditionsApplyConfiguration) GetResourceVersion() (value string, ok bool) {
	if v := b.fields.ResourceVersion; v != nil {
		return *v, true
	}
	return value, false
}

// ToUnstructured converts PreconditionsApplyConfiguration to unstructured.
func (b *PreconditionsApplyConfiguration) ToUnstructured() interface{} {
	if b == nil {
		return nil
	}
	b.preMarshal()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(&b.fields)
	if err != nil {
		panic(err)
	}
	return u
}

// FromUnstructured converts unstructured to PreconditionsApplyConfiguration, replacing the contents
// of PreconditionsApplyConfiguration.
func (b *PreconditionsApplyConfiguration) FromUnstructured(u map[string]interface{}) error {
	m := &preconditionsFields{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u, m)
	if err != nil {
		return err
	}
	b.fields = *m
	b.postUnmarshal()
	return nil
}

// MarshalJSON marshals PreconditionsApplyConfiguration to JSON.
func (b *PreconditionsApplyConfiguration) MarshalJSON() ([]byte, error) {
	b.preMarshal()
	return json.Marshal(b.fields)
}

// UnmarshalJSON unmarshals JSON into PreconditionsApplyConfiguration, replacing the contents of
// PreconditionsApplyConfiguration.
func (b *PreconditionsApplyConfiguration) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &b.fields); err != nil {
		return err
	}
	b.postUnmarshal()
	return nil
}

// PreconditionsList represents a listAlias of PreconditionsApplyConfiguration.
type PreconditionsList []*PreconditionsApplyConfiguration

// PreconditionsList represents a map of PreconditionsApplyConfiguration.
type PreconditionsMap map[string]PreconditionsApplyConfiguration

func (b *PreconditionsApplyConfiguration) preMarshal() {
}
func (b *PreconditionsApplyConfiguration) postUnmarshal() {
}
