/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by typebuilder-gen. DO NOT EDIT.

package v1beta1

import (
	json "encoding/json"

	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/client-go/typebuilders/meta/v1"
)

// EvictionBuilder represents an declarative configuration of the Eviction type for use
// with apply.
type EvictionBuilder struct {
	typeMeta v1.TypeMetaBuilder // inlined type
	fields   *evictionFields
}

// evictionFields is used by EvictionBuilder for json marshalling and unmarshalling.
// Is the source-of-truth for all fields except inlined fields.
// Inline fields are copied in from their builder type in EvictionBuilder before marshalling, and
// are copied out to the builder type in EvictionBuilder after unmarshalling.
// Inlined builder types cannot be embedded because they do not expose their fields directly.
type evictionFields struct {
	Kind          *string                  `json:"kind,omitempty"`       // inlined EvictionBuilder.typeMeta.Kind field
	APIVersion    *string                  `json:"apiVersion,omitempty"` // inlined EvictionBuilder.typeMeta.APIVersion field
	ObjectMeta    *v1.ObjectMetaBuilder    `json:"metadata,omitempty"`
	DeleteOptions *v1.DeleteOptionsBuilder `json:"deleteOptions,omitempty"`
}

func (b *EvictionBuilder) ensureInitialized() {
	if b.fields == nil {
		b.fields = &evictionFields{}
	}
}

// Eviction constructs an declarative configuration of the Eviction type for use with
// apply.
// Provided as a convenience.
func Eviction() EvictionBuilder {
	return EvictionBuilder{fields: &evictionFields{}}
}

// SetTypeMeta sets the TypeMeta field in the declarative configuration to the given value.
func (b EvictionBuilder) SetTypeMeta(value v1.TypeMetaBuilder) EvictionBuilder {
	b.ensureInitialized()
	b.typeMeta = value
	return b
}

// RemoveTypeMeta removes the TypeMeta field from the declarative configuration.
func (b EvictionBuilder) RemoveTypeMeta() EvictionBuilder {
	b.ensureInitialized()
	b.typeMeta = v1.TypeMetaBuilder{}
	return b
}

// GetTypeMeta gets the TypeMeta field from the declarative configuration.
func (b EvictionBuilder) GetTypeMeta() (value v1.TypeMetaBuilder, ok bool) {
	b.ensureInitialized()
	return b.typeMeta, true
}

// SetObjectMeta sets the ObjectMeta field in the declarative configuration to the given value.
func (b EvictionBuilder) SetObjectMeta(value v1.ObjectMetaBuilder) EvictionBuilder {
	b.ensureInitialized()
	b.fields.ObjectMeta = &value
	return b
}

// RemoveObjectMeta removes the ObjectMeta field from the declarative configuration.
func (b EvictionBuilder) RemoveObjectMeta() EvictionBuilder {
	b.ensureInitialized()
	b.fields.ObjectMeta = nil
	return b
}

// GetObjectMeta gets the ObjectMeta field from the declarative configuration.
func (b EvictionBuilder) GetObjectMeta() (value v1.ObjectMetaBuilder, ok bool) {
	b.ensureInitialized()
	if v := b.fields.ObjectMeta; v != nil {
		return *v, true
	}
	return value, false
}

// SetDeleteOptions sets the DeleteOptions field in the declarative configuration to the given value.
func (b EvictionBuilder) SetDeleteOptions(value v1.DeleteOptionsBuilder) EvictionBuilder {
	b.ensureInitialized()
	b.fields.DeleteOptions = &value
	return b
}

// RemoveDeleteOptions removes the DeleteOptions field from the declarative configuration.
func (b EvictionBuilder) RemoveDeleteOptions() EvictionBuilder {
	b.ensureInitialized()
	b.fields.DeleteOptions = nil
	return b
}

// GetDeleteOptions gets the DeleteOptions field from the declarative configuration.
func (b EvictionBuilder) GetDeleteOptions() (value v1.DeleteOptionsBuilder, ok bool) {
	b.ensureInitialized()
	if v := b.fields.DeleteOptions; v != nil {
		return *v, true
	}
	return value, false
}

// ToUnstructured converts EvictionBuilder to unstructured.
func (b *EvictionBuilder) ToUnstructured() interface{} {
	if b == nil {
		return nil
	}
	b.ensureInitialized()
	b.preMarshal()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(b.fields)
	if err != nil {
		panic(err)
	}
	return u
}

// FromUnstructured converts unstructured to EvictionBuilder, replacing the contents
// of EvictionBuilder.
func (b *EvictionBuilder) FromUnstructured(u map[string]interface{}) error {
	m := &evictionFields{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u, m)
	if err != nil {
		return err
	}
	b.fields = m
	b.postUnmarshal()
	return nil
}

// MarshalJSON marshals EvictionBuilder to JSON.
func (b *EvictionBuilder) MarshalJSON() ([]byte, error) {
	u := &unstructured.Unstructured{Object: b.ToUnstructured().(map[string]interface{})}
	return u.MarshalJSON()
}

// UnmarshalJSON unmarshals JSON into EvictionBuilder, replacing the contents of
// EvictionBuilder.
func (b *EvictionBuilder) UnmarshalJSON(data []byte) error {
	b.ensureInitialized()
	if err := json.Unmarshal(data, b.fields); err != nil {
		return err
	}
	b.postUnmarshal()
	return nil
}

// EvictionList represents a list of EvictionBuilder.
// Provided as a convenience.
type EvictionList []EvictionBuilder

// EvictionList represents a map of EvictionBuilder.
// Provided as a convenience.
type EvictionMap map[string]EvictionBuilder

func (b *EvictionBuilder) preMarshal() {
	if v, ok := b.typeMeta.GetKind(); ok {
		b.fields.Kind = &v
	}
	if v, ok := b.typeMeta.GetAPIVersion(); ok {
		b.fields.APIVersion = &v
	}
}
func (b *EvictionBuilder) postUnmarshal() {
	if b.fields.Kind != nil {
		b.typeMeta.SetKind(*b.fields.Kind)
	}
	if b.fields.APIVersion != nil {
		b.typeMeta.SetAPIVersion(*b.fields.APIVersion)
	}
}
