//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by validation-gen. DO NOT EDIT.

package v1

import (
	v1 "k8s.io/api/apps/v1"
	validation "k8s.io/apimachinery/pkg/util/validation"
	field "k8s.io/apimachinery/pkg/util/validation/field"
)

func Validate_StatefulSet(in *v1.StatefulSet, fldPath *field.Path) (errs field.ErrorList) {
	errs = append(errs, Validate_StatefulSetSpec(&in.Spec, fldPath.Child("spec"))...)
	return errs
}

func Validate_StatefulSetSpec(in *v1.StatefulSetSpec, fldPath *field.Path) (errs field.ErrorList) {
	errs = append(errs, validation.ValidateMaxLength(fldPath.Child("serviceName"), in.ServiceName, 128)...)
	return errs
}

func Validate_StatefulSetList(in *v1.StatefulSetList, fldPath *field.Path) (errs field.ErrorList) {
	for k := range in.Items {
		c := &in.Items[k]
		errs = append(errs, Validate_StatefulSet(c, fldPath.Index(k))...)
	}
	return errs
}
