/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by typebuilder-gen. DO NOT EDIT.

package v1

import (
	json "encoding/json"

	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/client-go/typebuilders/meta/v1"
)

// SubjectAccessReviewBuilder represents an declarative configuration of the SubjectAccessReview type for use
// with apply.
type SubjectAccessReviewBuilder struct {
	typeMeta v1.TypeMetaBuilder // inlined type
	fields   *subjectAccessReviewFields
}

// subjectAccessReviewFields is used by SubjectAccessReviewBuilder for json marshalling and unmarshalling.
// Is the source-of-truth for all fields except inlined fields.
// Inline fields are copied in from their builder type in SubjectAccessReviewBuilder before marshalling, and
// are copied out to the builder type in SubjectAccessReviewBuilder after unmarshalling.
// Inlined builder types cannot be embedded because they do not expose their fields directly.
type subjectAccessReviewFields struct {
	Kind       *string                           `json:"kind,omitempty"`       // inlined SubjectAccessReviewBuilder.typeMeta.Kind field
	APIVersion *string                           `json:"apiVersion,omitempty"` // inlined SubjectAccessReviewBuilder.typeMeta.APIVersion field
	ObjectMeta *v1.ObjectMetaBuilder             `json:"metadata,omitempty"`
	Spec       *SubjectAccessReviewSpecBuilder   `json:"spec,omitempty"`
	Status     *SubjectAccessReviewStatusBuilder `json:"status,omitempty"`
}

func (b *SubjectAccessReviewBuilder) ensureInitialized() {
	if b.fields == nil {
		b.fields = &subjectAccessReviewFields{}
	}
}

// SubjectAccessReview constructs an declarative configuration of the SubjectAccessReview type for use with
// apply.
// Provided as a convenience.
func SubjectAccessReview() SubjectAccessReviewBuilder {
	return SubjectAccessReviewBuilder{fields: &subjectAccessReviewFields{}}
}

// SetTypeMeta sets the TypeMeta field in the declarative configuration to the given value.
func (b SubjectAccessReviewBuilder) SetTypeMeta(value v1.TypeMetaBuilder) SubjectAccessReviewBuilder {
	b.ensureInitialized()
	b.typeMeta = value
	return b
}

// RemoveTypeMeta removes the TypeMeta field from the declarative configuration.
func (b SubjectAccessReviewBuilder) RemoveTypeMeta() SubjectAccessReviewBuilder {
	b.ensureInitialized()
	b.typeMeta = v1.TypeMetaBuilder{}
	return b
}

// GetTypeMeta gets the TypeMeta field from the declarative configuration.
func (b SubjectAccessReviewBuilder) GetTypeMeta() (value v1.TypeMetaBuilder, ok bool) {
	b.ensureInitialized()
	return b.typeMeta, true
}

// SetObjectMeta sets the ObjectMeta field in the declarative configuration to the given value.
func (b SubjectAccessReviewBuilder) SetObjectMeta(value v1.ObjectMetaBuilder) SubjectAccessReviewBuilder {
	b.ensureInitialized()
	b.fields.ObjectMeta = &value
	return b
}

// RemoveObjectMeta removes the ObjectMeta field from the declarative configuration.
func (b SubjectAccessReviewBuilder) RemoveObjectMeta() SubjectAccessReviewBuilder {
	b.ensureInitialized()
	b.fields.ObjectMeta = nil
	return b
}

// GetObjectMeta gets the ObjectMeta field from the declarative configuration.
func (b SubjectAccessReviewBuilder) GetObjectMeta() (value v1.ObjectMetaBuilder, ok bool) {
	b.ensureInitialized()
	if v := b.fields.ObjectMeta; v != nil {
		return *v, true
	}
	return value, false
}

// SetSpec sets the Spec field in the declarative configuration to the given value.
func (b SubjectAccessReviewBuilder) SetSpec(value SubjectAccessReviewSpecBuilder) SubjectAccessReviewBuilder {
	b.ensureInitialized()
	b.fields.Spec = &value
	return b
}

// RemoveSpec removes the Spec field from the declarative configuration.
func (b SubjectAccessReviewBuilder) RemoveSpec() SubjectAccessReviewBuilder {
	b.ensureInitialized()
	b.fields.Spec = nil
	return b
}

// GetSpec gets the Spec field from the declarative configuration.
func (b SubjectAccessReviewBuilder) GetSpec() (value SubjectAccessReviewSpecBuilder, ok bool) {
	b.ensureInitialized()
	if v := b.fields.Spec; v != nil {
		return *v, true
	}
	return value, false
}

// SetStatus sets the Status field in the declarative configuration to the given value.
func (b SubjectAccessReviewBuilder) SetStatus(value SubjectAccessReviewStatusBuilder) SubjectAccessReviewBuilder {
	b.ensureInitialized()
	b.fields.Status = &value
	return b
}

// RemoveStatus removes the Status field from the declarative configuration.
func (b SubjectAccessReviewBuilder) RemoveStatus() SubjectAccessReviewBuilder {
	b.ensureInitialized()
	b.fields.Status = nil
	return b
}

// GetStatus gets the Status field from the declarative configuration.
func (b SubjectAccessReviewBuilder) GetStatus() (value SubjectAccessReviewStatusBuilder, ok bool) {
	b.ensureInitialized()
	if v := b.fields.Status; v != nil {
		return *v, true
	}
	return value, false
}

// ToUnstructured converts SubjectAccessReviewBuilder to unstructured.
func (b *SubjectAccessReviewBuilder) ToUnstructured() interface{} {
	if b == nil {
		return nil
	}
	b.ensureInitialized()
	b.preMarshal()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(b.fields)
	if err != nil {
		panic(err)
	}
	return u
}

// FromUnstructured converts unstructured to SubjectAccessReviewBuilder, replacing the contents
// of SubjectAccessReviewBuilder.
func (b *SubjectAccessReviewBuilder) FromUnstructured(u map[string]interface{}) error {
	m := &subjectAccessReviewFields{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u, m)
	if err != nil {
		return err
	}
	b.fields = m
	b.postUnmarshal()
	return nil
}

// MarshalJSON marshals SubjectAccessReviewBuilder to JSON.
func (b *SubjectAccessReviewBuilder) MarshalJSON() ([]byte, error) {
	b.ensureInitialized()
	b.preMarshal()
	return json.Marshal(b.fields)
}

// UnmarshalJSON unmarshals JSON into SubjectAccessReviewBuilder, replacing the contents of
// SubjectAccessReviewBuilder.
func (b *SubjectAccessReviewBuilder) UnmarshalJSON(data []byte) error {
	b.ensureInitialized()
	if err := json.Unmarshal(data, b.fields); err != nil {
		return err
	}
	b.postUnmarshal()
	return nil
}

// SubjectAccessReviewList represents a list of SubjectAccessReviewBuilder.
// Provided as a convenience.
type SubjectAccessReviewList []SubjectAccessReviewBuilder

// SubjectAccessReviewList represents a map of SubjectAccessReviewBuilder.
// Provided as a convenience.
type SubjectAccessReviewMap map[string]SubjectAccessReviewBuilder

func (b *SubjectAccessReviewBuilder) preMarshal() {
	if v, ok := b.typeMeta.GetKind(); ok {
		b.fields.Kind = &v
	}
	if v, ok := b.typeMeta.GetAPIVersion(); ok {
		b.fields.APIVersion = &v
	}
}
func (b *SubjectAccessReviewBuilder) postUnmarshal() {
	if b.fields.Kind != nil {
		b.typeMeta.SetKind(*b.fields.Kind)
	}
	if b.fields.APIVersion != nil {
		b.typeMeta.SetAPIVersion(*b.fields.APIVersion)
	}
}
