/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2beta2

import (
	json "encoding/json"

	v2beta2 "k8s.io/api/autoscaling/v2beta2"
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// HorizontalPodAutoscalerConditionApplyConfiguration represents an declarative configuration of the HorizontalPodAutoscalerCondition type for use
// with apply.
type HorizontalPodAutoscalerConditionApplyConfiguration struct {
	fields horizontalPodAutoscalerConditionFields
}

// HorizontalPodAutoscalerConditionApplyConfiguration constructs an declarative configuration of the HorizontalPodAutoscalerCondition type for use with
// apply.
func HorizontalPodAutoscalerCondition() *HorizontalPodAutoscalerConditionApplyConfiguration {
	return &HorizontalPodAutoscalerConditionApplyConfiguration{}
}

// horizontalPodAutoscalerConditionFields owns all fields except inlined fields.
// Inline fields are owned by their respective inline type in HorizontalPodAutoscalerConditionApplyConfiguration.
// They are copied to this type before marshalling, and are copied out
// after unmarshalling. The inlined types cannot be embedded because they do
// not expose their fields directly.
type horizontalPodAutoscalerConditionFields struct {
	Type               *v2beta2.HorizontalPodAutoscalerConditionType `json:"type,omitempty"`
	Status             *v1.ConditionStatus                           `json:"status,omitempty"`
	LastTransitionTime *metav1.Time                                  `json:"lastTransitionTime,omitempty"`
	Reason             *string                                       `json:"reason,omitempty"`
	Message            *string                                       `json:"message,omitempty"`
}

// SetType sets the Type field in the declarative configuration to the given value.
func (b *HorizontalPodAutoscalerConditionApplyConfiguration) SetType(value v2beta2.HorizontalPodAutoscalerConditionType) *HorizontalPodAutoscalerConditionApplyConfiguration {
	b.fields.Type = &value
	return b
}

// RemoveType removes the Type field from the declarative configuration.
func (b *HorizontalPodAutoscalerConditionApplyConfiguration) RemoveType() *HorizontalPodAutoscalerConditionApplyConfiguration {
	b.fields.Type = nil
	return b
}

// GetType gets the Type field from the declarative configuration.
func (b *HorizontalPodAutoscalerConditionApplyConfiguration) GetType() (value v2beta2.HorizontalPodAutoscalerConditionType, ok bool) {
	if v := b.fields.Type; v != nil {
		return *v, true
	}
	return value, false
}

// SetStatus sets the Status field in the declarative configuration to the given value.
func (b *HorizontalPodAutoscalerConditionApplyConfiguration) SetStatus(value v1.ConditionStatus) *HorizontalPodAutoscalerConditionApplyConfiguration {
	b.fields.Status = &value
	return b
}

// RemoveStatus removes the Status field from the declarative configuration.
func (b *HorizontalPodAutoscalerConditionApplyConfiguration) RemoveStatus() *HorizontalPodAutoscalerConditionApplyConfiguration {
	b.fields.Status = nil
	return b
}

// GetStatus gets the Status field from the declarative configuration.
func (b *HorizontalPodAutoscalerConditionApplyConfiguration) GetStatus() (value v1.ConditionStatus, ok bool) {
	if v := b.fields.Status; v != nil {
		return *v, true
	}
	return value, false
}

// SetLastTransitionTime sets the LastTransitionTime field in the declarative configuration to the given value.
func (b *HorizontalPodAutoscalerConditionApplyConfiguration) SetLastTransitionTime(value metav1.Time) *HorizontalPodAutoscalerConditionApplyConfiguration {
	b.fields.LastTransitionTime = &value
	return b
}

// RemoveLastTransitionTime removes the LastTransitionTime field from the declarative configuration.
func (b *HorizontalPodAutoscalerConditionApplyConfiguration) RemoveLastTransitionTime() *HorizontalPodAutoscalerConditionApplyConfiguration {
	b.fields.LastTransitionTime = nil
	return b
}

// GetLastTransitionTime gets the LastTransitionTime field from the declarative configuration.
func (b *HorizontalPodAutoscalerConditionApplyConfiguration) GetLastTransitionTime() (value metav1.Time, ok bool) {
	if v := b.fields.LastTransitionTime; v != nil {
		return *v, true
	}
	return value, false
}

// SetReason sets the Reason field in the declarative configuration to the given value.
func (b *HorizontalPodAutoscalerConditionApplyConfiguration) SetReason(value string) *HorizontalPodAutoscalerConditionApplyConfiguration {
	b.fields.Reason = &value
	return b
}

// RemoveReason removes the Reason field from the declarative configuration.
func (b *HorizontalPodAutoscalerConditionApplyConfiguration) RemoveReason() *HorizontalPodAutoscalerConditionApplyConfiguration {
	b.fields.Reason = nil
	return b
}

// GetReason gets the Reason field from the declarative configuration.
func (b *HorizontalPodAutoscalerConditionApplyConfiguration) GetReason() (value string, ok bool) {
	if v := b.fields.Reason; v != nil {
		return *v, true
	}
	return value, false
}

// SetMessage sets the Message field in the declarative configuration to the given value.
func (b *HorizontalPodAutoscalerConditionApplyConfiguration) SetMessage(value string) *HorizontalPodAutoscalerConditionApplyConfiguration {
	b.fields.Message = &value
	return b
}

// RemoveMessage removes the Message field from the declarative configuration.
func (b *HorizontalPodAutoscalerConditionApplyConfiguration) RemoveMessage() *HorizontalPodAutoscalerConditionApplyConfiguration {
	b.fields.Message = nil
	return b
}

// GetMessage gets the Message field from the declarative configuration.
func (b *HorizontalPodAutoscalerConditionApplyConfiguration) GetMessage() (value string, ok bool) {
	if v := b.fields.Message; v != nil {
		return *v, true
	}
	return value, false
}

// ToUnstructured converts HorizontalPodAutoscalerConditionApplyConfiguration to unstructured.
func (b *HorizontalPodAutoscalerConditionApplyConfiguration) ToUnstructured() interface{} {
	if b == nil {
		return nil
	}
	b.preMarshal()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(&b.fields)
	if err != nil {
		panic(err)
	}
	return u
}

// FromUnstructured converts unstructured to HorizontalPodAutoscalerConditionApplyConfiguration, replacing the contents
// of HorizontalPodAutoscalerConditionApplyConfiguration.
func (b *HorizontalPodAutoscalerConditionApplyConfiguration) FromUnstructured(u map[string]interface{}) error {
	m := &horizontalPodAutoscalerConditionFields{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u, m)
	if err != nil {
		return err
	}
	b.fields = *m
	b.postUnmarshal()
	return nil
}

// MarshalJSON marshals HorizontalPodAutoscalerConditionApplyConfiguration to JSON.
func (b *HorizontalPodAutoscalerConditionApplyConfiguration) MarshalJSON() ([]byte, error) {
	b.preMarshal()
	return json.Marshal(b.fields)
}

// UnmarshalJSON unmarshals JSON into HorizontalPodAutoscalerConditionApplyConfiguration, replacing the contents of
// HorizontalPodAutoscalerConditionApplyConfiguration.
func (b *HorizontalPodAutoscalerConditionApplyConfiguration) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &b.fields); err != nil {
		return err
	}
	b.postUnmarshal()
	return nil
}

// HorizontalPodAutoscalerConditionList represents a listAlias of HorizontalPodAutoscalerConditionApplyConfiguration.
type HorizontalPodAutoscalerConditionList []*HorizontalPodAutoscalerConditionApplyConfiguration

// HorizontalPodAutoscalerConditionList represents a map of HorizontalPodAutoscalerConditionApplyConfiguration.
type HorizontalPodAutoscalerConditionMap map[string]HorizontalPodAutoscalerConditionApplyConfiguration

func (b *HorizontalPodAutoscalerConditionApplyConfiguration) preMarshal() {
}
func (b *HorizontalPodAutoscalerConditionApplyConfiguration) postUnmarshal() {
}
