/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2beta2

import (
	v2beta2 "k8s.io/api/autoscaling/v2beta2"
)

// MetricStatusApplyConfiguration represents an declarative configuration of the MetricStatus type for use
// with apply.
type MetricStatusApplyConfiguration struct {
	Type              *v2beta2.MetricSourceType                        `json:"type,omitempty"`
	Object            *ObjectMetricStatusApplyConfiguration            `json:"object,omitempty"`
	Pods              *PodsMetricStatusApplyConfiguration              `json:"pods,omitempty"`
	Resource          *ResourceMetricStatusApplyConfiguration          `json:"resource,omitempty"`
	ContainerResource *ContainerResourceMetricStatusApplyConfiguration `json:"containerResource,omitempty"`
	External          *ExternalMetricStatusApplyConfiguration          `json:"external,omitempty"`
}

// MetricStatusApplyConfiguration constructs an declarative configuration of the MetricStatus type for use with
// apply.
func MetricStatus() *MetricStatusApplyConfiguration {
	return &MetricStatusApplyConfiguration{}
}

// SetType sets the Type field in the declarative configuration to the given value.
func (b *MetricStatusApplyConfiguration) SetType(value v2beta2.MetricSourceType) *MetricStatusApplyConfiguration {
	b.Type = &value
	return b
}

// SetObject sets the Object field in the declarative configuration to the given value.
func (b *MetricStatusApplyConfiguration) SetObject(value *ObjectMetricStatusApplyConfiguration) *MetricStatusApplyConfiguration {
	b.Object = value
	return b
}

// SetPods sets the Pods field in the declarative configuration to the given value.
func (b *MetricStatusApplyConfiguration) SetPods(value *PodsMetricStatusApplyConfiguration) *MetricStatusApplyConfiguration {
	b.Pods = value
	return b
}

// SetResource sets the Resource field in the declarative configuration to the given value.
func (b *MetricStatusApplyConfiguration) SetResource(value *ResourceMetricStatusApplyConfiguration) *MetricStatusApplyConfiguration {
	b.Resource = value
	return b
}

// SetContainerResource sets the ContainerResource field in the declarative configuration to the given value.
func (b *MetricStatusApplyConfiguration) SetContainerResource(value *ContainerResourceMetricStatusApplyConfiguration) *MetricStatusApplyConfiguration {
	b.ContainerResource = value
	return b
}

// SetExternal sets the External field in the declarative configuration to the given value.
func (b *MetricStatusApplyConfiguration) SetExternal(value *ExternalMetricStatusApplyConfiguration) *MetricStatusApplyConfiguration {
	b.External = value
	return b
}
